import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {createClient} from "npm:@supabase/supabase-js@2";
const S=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(S,K,{auth:{persistSession:false}}),ORIGINS=new Set(["https://stationforhumanity.com","https://www.stationforhumanity.com"]);
const safe=(v:any,n=500)=>String(v??"").trim().slice(0,n);
function cors(o:string|null){const x=o&&ORIGINS.has(o)?o:"https://stationforhumanity.com";return{"Access-Control-Allow-Origin":x,"Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Vary":"Origin"}}
function out(s:number,b:any,o:string|null){return new Response(JSON.stringify(b),{status:s,headers:{...cors(o),"content-type":"application/json; charset=utf-8"}})}
function graph(version:string,path:string){return `https://graph.facebook.com/${version.replace(/^\/+|\/+$/g,"")}/${path.replace(/^\//,"")}`}
async function meta(token:string,version:string,path:string,method="GET",body?:any){const r=await fetch(graph(version,path),{method,headers:{Authorization:`Bearer ${token}`,...(body?{"content-type":"application/json"}:{})},...(body?{body:JSON.stringify(body)}:{})});const j=await r.json().catch(()=>({}));if(!r.ok||j?.error)throw Error(j?.error?.message||`meta_${r.status}`);return j}
async function inst(b:any){if(b.instance_id){const {data}=await db.from("leadbot_instances").select("*").eq("id",b.instance_id).maybeSingle();return data}if(b.order_no){const {data:o}=await db.from("orders").select("id").eq("order_no",Number(b.order_no)).maybeSingle();if(!o)return null;const {data}=await db.from("leadbot_instances").select("*").eq("order_id",o.id).maybeSingle();return data}const {data}=await db.from("leadbot_instances").select("*").order("created_at",{ascending:false}).limit(1).maybeSingle();return data}
function secret(){return (crypto.randomUUID()+crypto.randomUUID()).replaceAll("-","")}
async function store(id:string,kind:string,value:string){const {error}=await db.rpc("leadbot_store_secret",{p_instance_id:id,p_kind:kind,p_value:value});if(error)throw Error(`${kind}:${error.message}`)}

Deno.serve(async req=>{const origin=req.headers.get("origin");if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(origin)});if(req.method!=="POST")return out(405,{ok:false,error:"method_not_allowed"},origin);if(origin&&!ORIGINS.has(origin))return out(403,{ok:false,error:"origin_not_allowed"},origin);const jwt=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");const {data:u,error:ue}=await db.auth.getUser(jwt);if(ue||!u?.user)return out(401,{ok:false,error:"invalid_session"},origin);const {data:p}=await db.from("profiles").select("role,status").eq("id",u.user.id).maybeSingle();if(!p||p.status!=="active"||p.role!=="admin")return out(403,{ok:false,error:"admin_required"},origin);let b:any;try{b=await req.json()}catch{return out(400,{ok:false,error:"invalid_json"},origin)}const i=await inst(b);if(!i)return out(404,{ok:false,error:"leadbot_instance_not_found"},origin);const action=safe(b.action,50);
if(action==="snapshot"){const {data:r}=await db.rpc("leadbot_refresh_readiness",{p_instance_id:i.id});const {data:s}=await db.rpc("leadbot_get_secrets",{p_instance_id:i.id});let phone=null,subscription=null;if(s?.whatsapp_access_token&&s?.whatsapp_graph_version&&s?.whatsapp_phone_number_id){try{phone=await meta(s.whatsapp_access_token,s.whatsapp_graph_version,`${s.whatsapp_phone_number_id}?fields=display_phone_number,verified_name,quality_rating`)}catch{}}if(s?.whatsapp_access_token&&s?.whatsapp_graph_version&&s?.whatsapp_waba_id){try{subscription=await meta(s.whatsapp_access_token,s.whatsapp_graph_version,`${s.whatsapp_waba_id}/subscribed_apps`)}catch{}}return out(200,{ok:true,instance_id:i.id,public_slug:i.public_slug,status:i.status,business_name:i.business_name,readiness:r||i.readiness,phone,subscription},origin)}
if(action==="set_credentials"){const token=safe(b.access_token,10000),appSecret=safe(b.app_secret,10000),phoneId=safe(b.phone_number_id,100),wabaId=safe(b.waba_id,100),version=safe(b.graph_version,20);if(token.length<20||appSecret.length<8||!/^[0-9]+$/.test(phoneId)||!/^[0-9]+$/.test(wabaId)||!/^v\d+\.\d+$/.test(version))return out(400,{ok:false,error:"invalid_whatsapp_credentials"},origin);let phone;try{phone=await meta(token,version,`${phoneId}?fields=display_phone_number,verified_name,quality_rating`)}catch(e){return out(400,{ok:false,error:"whatsapp_credentials_invalid",detail:safe((e as any)?.message||e)},origin)}let verify=secret();try{await store(i.id,"whatsapp_access_token",token);await store(i.id,"whatsapp_app_secret",appSecret);await store(i.id,"whatsapp_phone_number_id",phoneId);await store(i.id,"whatsapp_waba_id",wabaId);await store(i.id,"whatsapp_graph_version",version);await store(i.id,"whatsapp_verify_token",verify)}catch(e){return out(500,{ok:false,error:"secret_store_failed",detail:safe((e as any)?.message||e)},origin)}const {data:r}=await db.rpc("leadbot_refresh_readiness",{p_instance_id:i.id});await db.from("audit_log").insert({actor_user_id:u.user.id,action:"leadbot.whatsapp_credentials_configured",entity_type:"leadbot_instance",entity_id:i.id,reason:"WhatsApp Cloud API credentials validated and stored in Vault",metadata:{order_id:i.order_id,phone_number_id:phoneId,waba_id:wabaId,graph_version:version,display_phone_number:phone?.display_phone_number||null,verified_name:phone?.verified_name||null}});return out(200,{ok:true,phone:{display_phone_number:phone?.display_phone_number,verified_name:phone?.verified_name,quality_rating:phone?.quality_rating},readiness:r},origin)}
if(action==="set_manager"){const phone=safe(b.phone,100).replace(/[^0-9]/g,"");if(phone.length<7||phone.length>20)return out(400,{ok:false,error:"invalid_manager_phone"},origin);try{await store(i.id,"whatsapp_manager_phone",phone)}catch(e){return out(500,{ok:false,error:"secret_store_failed",detail:safe((e as any)?.message||e)},origin)}const {data:r}=await db.rpc("leadbot_refresh_readiness",{p_instance_id:i.id});return out(200,{ok:true,readiness:r},origin)}
if(action==="activate"){const {data:s}=await db.rpc("leadbot_get_secrets",{p_instance_id:i.id});if(!s?.whatsapp_access_token||!s?.whatsapp_graph_version||!s?.whatsapp_waba_id||!s?.whatsapp_verify_token)return out(409,{ok:false,error:"whatsapp_credentials_missing"},origin);const callback=`${S}/functions/v1/leadbot-whatsapp?i=${encodeURIComponent(i.public_slug)}`;let sub;try{sub=await meta(s.whatsapp_access_token,s.whatsapp_graph_version,`${s.whatsapp_waba_id}/subscribed_apps`,"POST",{override_callback_uri:callback,verify_token:s.whatsapp_verify_token})}catch(e){return out(502,{ok:false,error:"whatsapp_subscription_failed",detail:safe((e as any)?.message||e)},origin)}await db.from("leadbot_instances").update({status:"active",activated_at:i.activated_at||new Date().toISOString()}).eq("id",i.id);const {data:r}=await db.rpc("leadbot_refresh_readiness",{p_instance_id:i.id});await db.from("audit_log").insert({actor_user_id:u.user.id,action:"leadbot.whatsapp_activated",entity_type:"leadbot_instance",entity_id:i.id,reason:"WhatsApp Cloud API WABA subscribed to Station webhook",metadata:{order_id:i.order_id,waba_id:s.whatsapp_waba_id,phone_number_id:s.whatsapp_phone_number_id,graph_version:s.whatsapp_graph_version,webhook:callback}});return out(200,{ok:true,subscription:sub,webhook:callback,readiness:r},origin)}
if(action==="test_manager"){const {data:s}=await db.rpc("leadbot_get_secrets",{p_instance_id:i.id});if(!s?.whatsapp_access_token||!s?.whatsapp_graph_version||!s?.whatsapp_phone_number_id||!s?.whatsapp_manager_phone)return out(409,{ok:false,error:"whatsapp_manager_or_credentials_missing"},origin);try{await meta(s.whatsapp_access_token,s.whatsapp_graph_version,`${s.whatsapp_phone_number_id}/messages`,"POST",{messaging_product:"whatsapp",recipient_type:"individual",to:s.whatsapp_manager_phone,type:"text",text:{preview_url:false,body:`✅ Station LeadBot ${i.public_slug}: WhatsApp-канал менеджера подключён.`}})}catch(e){return out(502,{ok:false,error:"manager_message_failed",detail:safe((e as any)?.message||e),note:"Free-form WhatsApp messages can be restricted outside the customer-service window; use an approved template for proactive production notifications."},origin)}return out(200,{ok:true},origin)}
return out(400,{ok:false,error:"unknown_action"},origin)});