const langBtn=document.getElementById('langBtn');let lang=localStorage.getItem('sfh-lang')||(navigator.language?.toLowerCase().startsWith('ru')?'ru':'en');
const INTAKE_URL='https://xwapzjsnqyfiqbzeycyh.supabase.co/functions/v1/founding-ticket';
function applyLanguage(){document.documentElement.lang=lang;document.documentElement.dataset.lang=lang;document.querySelectorAll('[data-en][data-ru]').forEach(el=>el.textContent=el.dataset[lang]);langBtn.textContent=lang==='en'?'RU':'EN';localStorage.setItem('sfh-lang',lang);renderAllocation();updateDynamicText();}
langBtn.addEventListener('click',()=>{lang=lang==='en'?'ru':'en';applyLanguage()});

const modal=document.getElementById('joinModal');const roleInput=document.getElementById('ticketRole');const ticketTitle=document.getElementById('ticketTitle');const ticketForm=document.getElementById('ticketForm');const output=document.getElementById('ticketOutput');
const roleNames={need:{en:'I need something',ru:'Мне что-то нужно'},build:{en:'I can build',ru:'Я могу создавать'},resource:{en:'I have a resource',ru:'У меня есть ресурс'},contribute:{en:'I want to contribute',ru:'Я хочу внести вклад'},dream:{en:'I have a dream',ru:'У меня есть мечта'}};
function openTicket(role){roleInput.value=role;ticketTitle.textContent=roleNames[role]?.[lang]||'Join the Station';modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';}
function closeTicket(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow='';}
document.querySelectorAll('.role-card').forEach(card=>card.addEventListener('click',()=>openTicket(card.dataset.role)));
document.querySelectorAll('[data-close]').forEach(el=>el.addEventListener('click',closeTicket));
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeTicket()});

// Alpha 0.3: explicit consent + honeypot are injected here so the existing static HTML stays backwards-compatible.
const actions=ticketForm?.querySelector('.ticket-actions');
if(ticketForm&&actions){
  const hp=document.createElement('input');hp.type='text';hp.id='ticketWebsite';hp.name='website';hp.tabIndex=-1;hp.autocomplete='off';hp.setAttribute('aria-hidden','true');hp.style.cssText='position:absolute;left:-9999px;width:1px;height:1px;opacity:0';ticketForm.insertBefore(hp,actions);
  const consent=document.createElement('label');consent.id='ticketConsentLabel';consent.style.cssText='display:flex;grid-template-columns:auto 1fr;align-items:flex-start;gap:10px;cursor:pointer';consent.innerHTML='<input id="ticketConsent" type="checkbox" required style="width:auto;margin-top:3px"><span id="ticketConsentText"></span>';ticketForm.insertBefore(consent,actions);
}
function updateDynamicText(){const c=document.getElementById('ticketConsentText');if(c)c.textContent=lang==='ru'?'Я согласен отправить эти данные в Station for Humanity для обработки этой заявки.':'I agree to send this data to Station for Humanity for processing this request.';const submit=ticketForm?.querySelector('button[type="submit"]');if(submit&&!submit.dataset.busy)submit.textContent=lang==='ru'?'Отправить Founding Ticket':'Submit Founding Ticket';}

function buildTicket(){return{schema:'station-for-humanity/founding-ticket/v0.3',created_at:new Date().toISOString(),role:roleInput.value,name:document.getElementById('ticketName').value.trim()||null,region:document.getElementById('ticketRegion').value.trim()||null,statement:document.getElementById('ticketText').value.trim(),consent:document.getElementById('ticketConsent')?.checked===true,website:document.getElementById('ticketWebsite')?.value||'',article_0_acknowledged:true};}

function friendlyError(code){const ru={consent_required:'Нужно согласие на отправку данных.',invalid_role:'Некорректная роль.',statement_length:'Описание должно быть от 10 до 1500 символов.',field_too_long:'Одно из полей слишком длинное.',rate_limit:'Слишком много заявок с этого устройства. Попробуйте позже.',registration_closed:'Приём заявок временно закрыт.',origin_not_allowed:'Этот источник запроса не разрешён.'};const en={consent_required:'Consent is required.',invalid_role:'Invalid role.',statement_length:'Statement must be 10–1500 characters.',field_too_long:'One field is too long.',rate_limit:'Too many submissions from this device. Please try later.',registration_closed:'Registration is temporarily closed.',origin_not_allowed:'This request origin is not allowed.'};return (lang==='ru'?ru:en)[code]||(lang==='ru'?'Не удалось отправить заявку. Попробуйте ещё раз.':'Could not submit the ticket. Please try again.');}

ticketForm.addEventListener('submit',async e=>{e.preventDefault();const ticket=buildTicket();if(!ticket.consent){output.textContent=friendlyError('consent_required');return}const submit=ticketForm.querySelector('button[type="submit"]');submit.disabled=true;submit.dataset.busy='1';submit.textContent=lang==='ru'?'Отправляем…':'Submitting…';output.textContent=lang==='ru'?'Соединяемся со станцией…':'Connecting to the Station…';try{const res=await fetch(INTAKE_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(ticket)});const data=await res.json().catch(()=>({ok:false,error:'invalid_response'}));if(!res.ok||!data.ok){output.textContent=friendlyError(data.error);return}const result={...ticket,website:undefined,server_ticket:data.ticket};localStorage.setItem('sfh-last-ticket',JSON.stringify(result));output.textContent=(lang==='ru'?`Заявка принята. Номер: ${data.ticket.number}\nСтатус: ${data.ticket.status}`:`Ticket accepted. Number: ${data.ticket.number}\nStatus: ${data.ticket.status}`);ticketForm.dataset.submitted='1';}catch(err){output.textContent=lang==='ru'?'Сеть недоступна. Заявка не потеряна — попробуйте отправить ещё раз.':'Network unavailable. Your form is still here — please try again.';}finally{submit.disabled=false;delete submit.dataset.busy;updateDynamicText();}});

document.getElementById('copyTicket').addEventListener('click',async()=>{const ticket=buildTicket();delete ticket.website;const text=JSON.stringify(ticket,null,2);try{await navigator.clipboard.writeText(text);document.getElementById('copyTicket').textContent=lang==='ru'?'Скопировано':'Copied';setTimeout(()=>document.getElementById('copyTicket').textContent=lang==='ru'?'Скопировать JSON':'Copy JSON',1300)}catch{output.textContent=text}});

const allocationPlan=[['Creator / исполнители',35],['Module creators / авторы модулей',15],['Infrastructure + AI',10],['Dream Fund',10],['Platform development',20],['Social + reserve',10]];
function money(v){return new Intl.NumberFormat(lang==='ru'?'ru-RU':'en-US',{maximumFractionDigits:0}).format(v)}
function renderAllocation(){const input=document.getElementById('orderValue');const box=document.getElementById('allocation');if(!input||!box)return;const value=Math.max(0,Number(input.value)||0);box.innerHTML=allocationPlan.map(([name,pct])=>`<div class="allocation-row"><span>${name} · ${pct}%</span><span>${money(value*pct/100)}</span></div>`).join('');}
document.getElementById('orderValue')?.addEventListener('input',renderAllocation);

const saved=localStorage.getItem('sfh-last-ticket');if(saved){try{const parsed=JSON.parse(saved);if(parsed.server_ticket)output.textContent=(navigator.language?.toLowerCase().startsWith('ru')?`Последняя заявка: ${parsed.server_ticket.number}`:`Last ticket: ${parsed.server_ticket.number}`)}catch{}}
applyLanguage();