import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';

const SUPABASE_URL='https://xwapzjsnqyfiqbzeycyh.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_mVOY1vbk6e6jiBnT0VAX9w_sFXODDsi';
const SHEET_URL='https://docs.google.com/spreadsheets/d/1b64ke8DbJy6Q59smY1n8CducXsS1HaWK5UvT2OwsTek/edit';
const sb=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let timer=null;

async function invoke(action,payload={}){
  const {data,error}=await sb.functions.invoke('leadbot-admin',{body:{action,order_no:3,...payload}});
  if(error){let detail=error.message;try{if(error.context){const j=await error.context.json();detail=j.error+(j.detail?`: ${j.detail}`:'')}}catch{}throw new Error(detail)}
  if(!data?.ok)throw new Error(data?.error||'leadbot_admin_failed');
  return data;
}
function fmt(v){return v?new Date(v).toLocaleString('ru-RU'):'—'}
function money(v){return new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(Number(v||0))+' ₽'}
function check(label,ok,note=''){return `<div style="display:flex;justify-content:space-between;gap:12px;padding:8px 0;border-bottom:1px solid rgba(255,255,255,.06)"><span>${esc(label)}${note?`<small class="muted" style="display:block">${esc(note)}</small>`:''}</span><strong class="${ok?'on':'off'}">${ok?'READY':'WAITING'}</strong></div>`}
function secretRow(kind,label,placeholder='Вставить значение…'){return `<div style="display:grid;grid-template-columns:180px 1fr auto;gap:8px;align-items:end;margin:8px 0"><label style="margin:0"><span>${esc(label)}</span><input data-secret="${esc(kind)}" type="password" autocomplete="off" placeholder="${esc(placeholder)}"></label><div></div><button data-save-secret="${esc(kind)}" class="ghost">Сохранить</button></div>`}
function ensurePanel(){if($('#leadbotPanel'))return;const anchor=$('#factoryRequests')?.closest('.panel')||$('#financeHealthPanel');if(!anchor)return;const section=document.createElement('section');section.id='leadbotPanel';section.className='panel';section.style.marginTop='16px';section.innerHTML=`<div class="toolbar"><div><p class="eyebrow">PRODUCTION · LEADBOT</p><h2 style="margin:.25rem 0">ORD-000003 · Монтаж освещения</h2></div><button id="leadbotReload" class="primary">Обновить</button></div><p class="muted">Production-экземпляр. Telegram, CRM, API, калькулятор и интеграции контролируются здесь; секреты хранятся в Supabase Vault.</p><div id="leadbotBody">Загрузка…</div>`;anchor.insertAdjacentElement('afterend',section);$('#leadbotReload').onclick=load}
function statusOptions(current){return ['new','contacted','qualified','won','lost','spam'].map(x=>`<option value="${x}" ${x===current?'selected':''}>${x}</option>`).join('')}
function bind(){
  document.querySelectorAll('[data-save-secret]').forEach(b=>b.onclick=async()=>{const kind=b.dataset.saveSecret,input=document.querySelector(`[data-secret="${kind}"]`),value=input?.value?.trim();if(!value)return alert('Введите значение.');b.disabled=true;try{const d=await invoke('set_secret',{kind,value});input.value='';alert(kind==='bot_token'&&d.telegram?.username?`Telegram token принят. Бот: @${d.telegram.username}`:'Сохранено в Vault.');await load()}catch(e){alert(e.message)}finally{b.disabled=false}});
  $('#leadbotActivate')?.addEventListener('click',async()=>{try{const d=await invoke('activate');alert(`Webhook включён. Бот: @${d.bot?.username||'telegram_bot'}`);await load()}catch(e){alert(e.message)}});
  $('#leadbotClaim')?.addEventListener('click',async()=>{try{const d=await invoke('generate_claim');$('#claimCommand').textContent=d.command;$('#claimCommand').hidden=false;alert(`Отправьте боту: ${d.command}\nКод действует 30 минут.`)}catch(e){alert(e.message)}});
  $('#leadbotTestNotify')?.addEventListener('click',async()=>{try{await invoke('test_notification');alert('Тестовое сообщение отправлено менеджеру.')}catch(e){alert(e.message)}});
  $('#rotateApi')?.addEventListener('click',async()=>{if(!confirm('Создать новый client API token? Старый перестанет работать.'))return;try{const d=await invoke('rotate_api_token');prompt('Скопируйте token сейчас — повторно он не показывается:',d.token);await load()}catch(e){alert(e.message)}});
  $('#retryOutbox')?.addEventListener('click',async()=>{try{const d=await invoke('retry_outbox');alert(`В очередь повторно поставлено: ${d.queued}`);await load()}catch(e){alert(e.message)}});
  document.querySelectorAll('[data-lead-status]').forEach(s=>s.onchange=async()=>{s.disabled=true;try{await invoke('set_lead_status',{lead_id:s.dataset.leadStatus,status:s.value});await load()}catch(e){alert(e.message)}finally{s.disabled=false}});
  $('#saveCalc')?.addEventListener('click',async()=>{const base=Number($('#calcBase').value||0),per_point=Number($('#calcPoint').value||0),per_m2=Number($('#calcM2').value||0);try{await invoke('configure_calculator',{base,per_point,per_m2});alert('Тарифы калькулятора сохранены.');await load()}catch(e){alert(e.message)}});
}
function render(d){const i=d.instance||{},r=i.readiness||{},cfg=i.config||{},role=d.role||'',admin=role==='admin',rates=cfg.calculator?.rates||{};
  const readiness=`${check('Telegram bot token',r.bot_token)}${check('Telegram webhook secret',r.webhook_secret)}${check('Менеджерский чат',r.manager_chat_id)}${check('Google Sheets',r.google_sheets,'защищённый pull-feed')}${check('CRM',r.crm,'встроенный SFH MiniCRM')}${check('Webhook/API',r.webhook_api,'защищённый read-only API')}${check('AI FAQ',r.ai_faq)}${check('Калькулятор тарифов',r.calculator,'предварительная цена, не оферта')}`;
  const adminBlock=admin?`<section style="margin-top:18px"><h3>1. Telegram</h3>${secretRow('bot_token','Bot token','Токен от BotFather')}<div class="row"><button id="leadbotActivate" class="primary">Включить Telegram webhook</button><button id="leadbotClaim" class="ghost">Код привязки менеджера</button><button id="leadbotTestNotify" class="ghost">Тест менеджеру</button></div><pre id="claimCommand" hidden style="margin-top:10px"></pre><h3 style="margin-top:22px">2. Production integrations</h3><div class="row" style="flex-wrap:wrap"><a href="${SHEET_URL}" target="_blank" class="ghost" style="text-decoration:none;padding:11px 15px;border-radius:11px">Открыть Google Sheets</a><button id="rotateApi" class="ghost">Ротировать client API token</button><button id="retryOutbox" class="ghost">Повторить outbox</button></div><p class="muted">CRM и client API уже встроены в Station. Внешние CRM/webhook можно подключить дополнительно, не заменяя каноническую БД.</p><h3 style="margin-top:22px">3. AI FAQ provider</h3>${secretRow('ai_base_url','AI API base URL','OpenAI-compatible endpoint')}${secretRow('ai_model','AI model','Имя модели')}${secretRow('ai_api_key','AI API key')}<h3 style="margin-top:22px">4. Калькулятор</h3><div style="display:grid;grid-template-columns:repeat(3,minmax(120px,1fr));gap:8px"><label>База, ₽<input id="calcBase" type="number" min="0" value="${Number(rates.base||0)}"></label><label>За точку, ₽<input id="calcPoint" type="number" min="0" value="${Number(rates.per_point||0)}"></label><label>За м², ₽<input id="calcM2" type="number" min="0" value="${Number(rates.per_m2||0)}"></label></div><button id="saveCalc" class="ghost" style="margin-top:8px">Сохранить тарифы</button><p class="muted">Текущий baseline: ${money(rates.base||0)} база + ${money(rates.per_point||0)}/точка + ${money(rates.per_m2||0)}/м². Материалы и нестандартные условия не входят.</p></section>`:`<p class="muted">Секреты и production activation доступны только admin.</p>`;
  const leads=(d.leads||[]).map(x=>{const est=x.estimate?.available?money(x.estimate.amount):'без автоцены';return `<article class="card"><div class="card-head"><div><h3>LB-${String(x.lead_no).padStart(6,'0')} · ${esc(x.flow_code)}</h3><div class="meta">${fmt(x.created_at)} · ${esc(x.contact||'без контакта')} · ${esc(est)}</div></div><select data-lead-status="${esc(x.id)}">${statusOptions(x.status)}</select></div><pre>${esc(JSON.stringify(x.answers,null,2))}</pre></article>`}).join('')||'<article class="card muted">Лидов пока нет.</article>';
  const failed=(d.outbox||[]).filter(x=>x.status!=='succeeded');
  $('#leadbotBody').innerHTML=`<div class="hero-grid" style="margin-top:14px"><article class="panel metric"><small>INSTANCE</small><strong>${esc(String(i.status||'—').toUpperCase())}</strong><span>${esc(i.public_slug||'')}</span></article><article class="panel metric"><small>CORE</small><strong class="${r.core_ready?'on':'off'}">${r.core_ready?'READY':'WAITING'}</strong><span>Telegram runtime</span></article><article class="panel metric"><small>DELIVERY</small><strong class="${r.delivery_ready?'on':'off'}">${r.delivery_ready?'READY':'BLOCKED'}</strong><span>${r.delivery_ready?'все модули готовы':'остаётся AI/внешнее подтверждение'}</span></article><article class="panel metric"><small>ORDER</small><strong>${money(d.order?.quoted_amount)}</strong><span>${esc(d.factory?.status||'—')} · ${esc(d.order?.status||'—')}</span></article></div><div style="display:grid;grid-template-columns:minmax(260px,.8fr) minmax(320px,1.4fr);gap:18px;margin-top:16px"><div><h3>Готовность</h3>${readiness}</div><div>${adminBlock}</div></div><div class="toolbar" style="margin-top:22px"><h3>MiniCRM · лиды</h3><span class="muted">outbox problems: ${failed.length}</span></div><section class="cards">${leads}</section>`;
  bind();
}
async function load(){ensurePanel();const {data:{session}}=await sb.auth.getSession();if(!session||$('#consolePanel')?.hidden)return;try{render(await invoke('snapshot'))}catch(e){$('#leadbotBody').innerHTML=`<div class="off">ERROR · ${esc(e.message)}</div>`}}
ensurePanel();sb.auth.onAuthStateChange(()=>setTimeout(load,350));document.addEventListener('visibilitychange',()=>{if(!document.hidden)load()});setTimeout(load,900);timer=setInterval(load,30000);
