import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const URL='https://xwapzjsnqyfiqbzeycyh.supabase.co',KEY='sb_publishable_mVOY1vbk6e6jiBnT0VAX9w_sFXODDsi';
const sb=createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const WORKSPACE=new URLSearchParams(location.search).get('w')||'focus-biysk';const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));const money=v=>(Number(v)||0).toLocaleString('ru-RU',{maximumFractionDigits:0})+' ₽';
const planNames={rpk_monthly:'Помесячно · 999 ₽',rpk_halfyear:'6 месяцев · 5 390 ₽',rpk_year:'Год · 9 590 ₽'};let registryId=null;
async function api(action,payload={}){const {data,error}=await sb.functions.invoke('business-subscription',{body:{action,...payload}});if(error){let m=error.message;try{if(error.context){const j=await error.context.json();m=j.error+(j.detail?`: ${j.detail}`:'')}}catch{}throw new Error(m)}if(!data?.ok)throw new Error(data?.error||'subscription_error');return data}
function inject(){if(document.getElementById('addons'))return;const ws=document.getElementById('workspace');if(!ws)return;const sec=document.createElement('section');sec.id='addons';sec.className='panel section';sec.innerHTML=`<div class="section-head"><div><p class="eyebrow">РАСШИРЕНИЯ STATION</p><h2>Подключить возможности</h2></div><button id="addonsReload" class="ghost">Обновить</button></div><p class="muted">Основная работа РПК остаётся в одном кабинете. Дополнительную автоматизацию подключайте только когда она реально нужна.</p><div id="subscriptionState" class="empty-box"></div><div id="addonGrid" class="module-list" style="margin-top:16px"></div>`;const modules=document.getElementById('modules');if(modules)ws.insertBefore(sec,modules);else ws.appendChild(sec);const nav=document.getElementById('moduleNav');if(nav){const b=document.createElement('button');b.dataset.jump='addons';b.textContent='Подключить';b.onclick=()=>sec.scrollIntoView({behavior:'smooth',block:'start'});nav.appendChild(b)}document.getElementById('addonsReload').onclick=load}
function renderAddon(a){const price=a.pricing_kind==='one_time'&&a.price_from!=null?`от ${money(a.price_from)}`:a.pricing_kind==='monthly'&&a.price_from!=null?`от ${money(a.price_from)}/мес`:'по запросу';return `<div class="module-card"><div class="module-top"><strong>${esc(a.name_ru)}</strong><span class="badge">${esc(price)}</span></div><p>${esc(a.description_ru||'')}</p><button class="ghost addon-request" data-code="${esc(a.code)}">Хочу подключить →</button></div>`}
async function requestAddon(code){if(!registryId)return alert('Не удалось определить рабочее пространство.');const note=prompt('Комментарий или пожелание (можно оставить пустым)','')||'';try{const x=await api('request_addon',{workspace_id:registryId,addon_code:code,note});alert(x.already_exists?'Запрос уже есть — мы его не дублируем.':'Запрос сохранён. Он привязан к вашей компании.')}catch(e){alert(e.message)}}
async function load(){inject();const {data:{session}}=await sb.auth.getSession();if(!session)return;try{const x=await api('snapshot');const w=(x.workspaces||[]).find(v=>v.slug===WORKSPACE);registryId=w?.id||null;const sub=w?.subscription;document.getElementById('subscriptionState').innerHTML=sub?`<b>Подписка:</b> ${esc(planNames[sub.plan_code]||sub.plan_code)} · <b>${esc(sub.status)}</b>${x.payment_live===false?' · онлайн-списания пока выключены':''}`:'<b>Пилотный кабинет.</b> Тариф ещё не закреплён за этим ранним workspace; рабочие данные при этом сохраняются.';document.getElementById('addonGrid').innerHTML=(x.addons||[]).map(renderAddon).join('');document.querySelectorAll('.addon-request').forEach(b=>b.onclick=()=>requestAddon(b.dataset.code))}catch(e){document.getElementById('subscriptionState').textContent='Не удалось загрузить расширения: '+e.message}}
inject();sb.auth.onAuthStateChange(()=>setTimeout(load,500));setTimeout(load,850);