import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const URL='https://xwapzjsnqyfiqbzeycyh.supabase.co',KEY='sb_publishable_mVOY1vbk6e6jiBnT0VAX9w_sFXODDsi';
const sb=createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const WORKSPACE=new URLSearchParams(location.search).get('w')||'focus-biysk';const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));const money=v=>(Number(v)||0).toLocaleString('ru-RU',{maximumFractionDigits:0})+' ₽';
const planNames={rpk_monthly:'Помесячно · 999 ₽',rpk_halfyear:'6 месяцев · 5 390 ₽',rpk_year:'Год · 9 590 ₽'};let registryId=null;
async function api(action,payload={}){const {data,error}=await sb.functions.invoke('business-subscription',{body:{action,...payload}});if(error){let m=error.message;try{if(error.context){const j=await error.context.json();m=j.error+(j.detail?`: ${j.detail}`:'')}}catch{}throw new Error(m)}if(!data?.ok)throw new Error(data?.error||'subscription_error');return data}
function inject(){if(document.getElementById('addons'))return;const ws=document.getElementById('workspace');if(!ws)return;const sec=document.createElement('section');sec.id='addons';sec.className='panel section';sec.innerHTML=`<div class="section-head"><div><p class="eyebrow">РАСШИРЕНИЯ STATION</p><h2>Подключить возможности</h2></div><button id="addonsReload" class="ghost">Обновить</button></div><p class="muted">Основная работа РПК остаётся в одном кабинете. Дополнительную автоматизацию подключайте только когда она реально нужна.</p><div id="subscriptionState" class="empty-box"></div><div id="addonGrid" class="module-list" style="margin-top:16px"></div>`;const modules=document.getElementById('modules');if(modules)ws.insertBefore(sec,modules);else ws.appendChild(sec);const nav=document.getElementById('moduleNav');if(nav){const b=document.createElement('button');b.dataset.jump='addons';b.textContent='Подключить';b.onclick=()=>sec.scrollIntoView({behavior:'smooth',block:'start'});nav.appendChild(b)}document.getElementById('addonsReload').onclick=load}
function injectGuide(){if(document.getElementById('guide'))return;const ws=document.getElementById('workspace');if(!ws)return;const sec=document.createElement('section');sec.id='guide';sec.className='panel section';sec.innerHTML=`
<div class="section-head"><div><p class="eyebrow">ИНСТРУКЦИЯ RPK OS</p><h2>Как работать в CRM</h2></div><button id="guideStart" class="primary">Начать работу →</button></div>
<p class="muted">Не нужно изучать CRM целиком. Работайте по цепочке ниже — Station сама собирает общую картину для директора и менеджера.</p>
<div class="guide-grid">
<article class="guide-card"><b>1. Новый клиент</b><p>Если заказчик ещё не в базе: CRM → «+ Клиент». Внесите название и хотя бы один контакт.</p><button class="mini guide-jump" data-target="crm">Открыть CRM</button></article>
<article class="guide-card"><b>2. Новая заявка / заказ</b><p>Нажмите «+ Сделка»: клиент, что нужно сделать, сумма и себестоимость, если она уже известна.</p><button class="mini guide-jump" data-target="crm">Создать сделку</button></article>
<article class="guide-card"><b>3. Обязательно следующий шаг</b><p>Запишите, что делать дальше: позвонить, отправить макет, дождаться ответа. Тогда задача попадёт в «Сегодня».</p><button class="mini guide-jump" data-target="today">Что делать сегодня</button></article>
<article class="guide-card"><b>4. КП, счёт, задание</b><p>Документы храните в одной сделке. Старое КП можно загрузить в архив документов и использовать как основу нового.</p><button class="mini guide-jump" data-target="documents">Документы</button></article>
<article class="guide-card"><b>5. Макеты и производство</b><p>Старый макет загружайте в «Макеты», привязывайте к клиенту и запускайте переделку. Готовые задачи видны в производстве.</p><button class="mini guide-jump" data-target="archive">Макеты</button></article>
<article class="guide-card"><b>6. Реальные деньги</b><p>Когда деньги действительно пришли или ушли — отметьте приход/расход. Не путайте выставленный счёт с оплатой.</p><button class="mini guide-jump" data-target="money">Деньги</button></article>
<article class="guide-card"><b>7. Бухгалтер</b><p>Запросили счёт или акт — создайте запрос бухгалтеру. Получили документ — поменяйте статус. Email, MAX и звонки остаются в истории.</p><button class="mini guide-jump" data-target="documents">Бухгалтерия</button></article>
<article class="guide-card"><b>8. Завершение</b><p>Когда заказ готов и оплачен, переведите сделку в «Оплачено / завершено». Так отчёты не разъезжаются.</p><button class="mini guide-jump" data-target="crm">Закрыть сделку</button></article>
</div>
<div class="guide-routine"><strong>Ежедневно достаточно четырёх привычек</strong><span>утром открыть «Сегодня» → каждую новую заявку оформить сделкой → каждое обещание записать как следующий шаг → каждую реальную оплату/трату отметить в «Деньги».</span></div>`;
const today=document.getElementById('today');if(today)ws.insertBefore(sec,today);else ws.prepend(sec);const nav=document.getElementById('moduleNav');if(nav){const b=document.createElement('button');b.dataset.jump='guide';b.textContent='Как работать';b.onclick=()=>sec.scrollIntoView({behavior:'smooth',block:'start'});nav.insertBefore(b,nav.firstChild)}
const st=document.createElement('style');st.textContent=`.guide-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:18px}.guide-card{padding:17px;border:1px solid rgba(255,255,255,.08);border-radius:15px;background:rgba(255,255,255,.025)}.guide-card b{font-size:16px}.guide-card p{color:#9fb4c3;line-height:1.5;font-size:13px;min-height:58px}.guide-routine{margin-top:14px;padding:16px;border:1px solid rgba(92,233,255,.18);border-radius:14px;background:rgba(92,233,255,.05);display:grid;gap:6px}.guide-routine span{color:#b8ccd8;line-height:1.5}@media(max-width:760px){.guide-grid{grid-template-columns:1fr}.guide-card p{min-height:0}}.access-diagnostic{margin-top:12px;padding:12px;border:1px solid rgba(255,190,90,.25);border-radius:12px;background:rgba(255,190,90,.06);color:#d7e3ea;font-size:12px;line-height:1.5}`;document.head.appendChild(st);document.querySelectorAll('.guide-jump').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.target)?.scrollIntoView({behavior:'smooth',block:'start'}));document.getElementById('guideStart').onclick=()=>document.getElementById('today')?.scrollIntoView({behavior:'smooth',block:'start'})}
function renderAddon(a){const price=a.pricing_kind==='one_time'&&a.price_from!=null?`от ${money(a.price_from)}`:a.pricing_kind==='monthly'&&a.price_from!=null?`от ${money(a.price_from)}/мес`:'по запросу';return `<div class="module-card"><div class="module-top"><strong>${esc(a.name_ru)}</strong><span class="badge">${esc(price)}</span></div><p>${esc(a.description_ru||'')}</p><button class="ghost addon-request" data-code="${esc(a.code)}">Хочу подключить →</button></div>`}
async function requestAddon(code){if(!registryId)return alert('Не удалось определить рабочее пространство.');const note=prompt('Комментарий или пожелание (можно оставить пустым)','')||'';try{const x=await api('request_addon',{workspace_id:registryId,addon_code:code,note});alert(x.already_exists?'Запрос уже есть — мы его не дублируем.':'Запрос сохранён. Он привязан к вашей компании.')}catch(e){alert(e.message)}}
async function load(){inject();injectGuide();const {data:{session}}=await sb.auth.getSession();if(!session)return;try{const x=await api('snapshot');const w=(x.workspaces||[]).find(v=>v.slug===WORKSPACE);registryId=w?.id||null;const sub=w?.subscription;document.getElementById('subscriptionState').innerHTML=sub?`<b>Подписка:</b> ${esc(planNames[sub.plan_code]||sub.plan_code)} · <b>${esc(sub.status)}</b>${x.payment_live===false?' · онлайн-списания пока выключены':''}`:'<b>Пилотный кабинет.</b> Тариф ещё не закреплён за этим ранним workspace; рабочие данные при этом сохраняются.';document.getElementById('addonGrid').innerHTML=(x.addons||[]).map(renderAddon).join('');document.querySelectorAll('.addon-request').forEach(b=>b.onclick=()=>requestAddon(b.dataset.code))}catch(e){document.getElementById('subscriptionState').textContent='Не удалось загрузить расширения: '+e.message}}
async function diagnoseAccess(){const {data:{session}}=await sb.auth.getSession();if(!session)return;await new Promise(r=>setTimeout(r,1300));const auth=document.getElementById('authPanel'),workspace=document.getElementById('workspace');if(!auth||auth.hidden||!workspace?.hidden)return;let box=document.getElementById('accessDiagnostic');if(!box){box=document.createElement('div');box.id='accessDiagnostic';box.className='access-diagnostic';auth.appendChild(box)}box.textContent='Вход выполнен. Проверяем доступ к рабочему пространству…';try{await sb.auth.refreshSession();const invoke=async(fn)=>{const {data,error}=await sb.functions.invoke(fn,{body:{action:'snapshot',workspace_slug:WORKSPACE}});if(error)throw new Error(`${fn}: ${error.message}`);if(!data?.ok)throw new Error(`${fn}: ${data?.error||'ошибка доступа'}`);return data};await invoke('rpk-workspace');await invoke('rpk-os');box.textContent='Доступ подтверждён. Обновляем кабинет…';if(!sessionStorage.getItem('rpk-access-retry')){sessionStorage.setItem('rpk-access-retry','1');setTimeout(()=>location.reload(),250)}else{box.textContent='Сервер доступ разрешает, но интерфейс не открылся. Нажмите Ctrl+F5; если повторится — пришлите этот текст.'}}catch(e){box.textContent='Авторизация успешна, но сервер отклонил загрузку кабинета: '+e.message+' — сообщите этот текст администратору Station.'}}
inject();injectGuide();sb.auth.onAuthStateChange(()=>{setTimeout(load,500);setTimeout(diagnoseAccess,700)});setTimeout(load,850);setTimeout(diagnoseAccess,900);