import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const SHOP_ID=Deno.env.get("YOOKASSA_TEST_SHOP_ID")||"";
const SECRET=Deno.env.get("YOOKASSA_TEST_SECRET_KEY")||"";
const service=createClient(SUPABASE_URL,SERVICE_ROLE_KEY,{auth:{persistSession:false}});
const ORIGINS=new Set(["https://stationforhumanity.com","https://www.stationforhumanity.com"]);
const ROLES=new Set(["finance","admin"]);

function cors(origin:string|null){const o=origin&&ORIGINS.has(origin)?origin:"https://stationforhumanity.com";return{"Access-Control-Allow-Origin":o,"Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Vary":"Origin"};}
function json(status:number,body:unknown,origin:string|null){return new Response(JSON.stringify(body),{status,headers:{...cors(origin),"Content-Type":"application/json; charset=utf-8"}})}
function authHeader(){return `Basic ${btoa(`${SHOP_ID}:${SECRET}`)}`}
function safeRefund(r:any){return{id:r?.id||null,status:r?.status||null,amount:r?.amount||null,payment_id:r?.payment_id||null,created_at:r?.created_at||null,cancellation_details:r?.cancellation_details||null,metadata:r?.metadata||{}}}
async function audit(actor:string|null,action:string,type:string,id:string|null,reason:string|null,metadata:any={}){await service.from('audit_log').insert({actor_user_id:actor,action,entity_type:type,entity_id:id,reason,metadata});}
async function paymentGet(id:string){const r=await fetch(`https://api.yookassa.ru/v3/payments/${encodeURIComponent(id)}`,{headers:{Authorization:authHeader(),Accept:'application/json'}});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`payment_get_${r.status}:${body?.description||body?.type||'api_error'}`);return body;}
async function refundGet(id:string){const r=await fetch(`https://api.yookassa.ru/v3/refunds/${encodeURIComponent(id)}`,{headers:{Authorization:authHeader(),Accept:'application/json'}});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`refund_get_${r.status}:${body?.description||body?.type||'api_error'}`);return body;}
async function applyRefund(local:any,remote:any,actor:string|null){if(remote?.id!==local.external_refund_id)throw new Error('refund_id_mismatch');if(remote?.payment_id!==local.payment_external_id)throw new Error('refund_payment_mismatch');const amount=Number(remote?.amount?.value);if(remote?.amount?.currency!==local.currency||Math.abs(amount-Number(local.amount))>0.0001)throw new Error('refund_amount_mismatch');const safe=safeRefund(remote);await service.from('refunds').update({provider_status:remote.status,provider_payload:safe,status:remote.status==='succeeded'?'succeeded':remote.status==='canceled'?'canceled':'processing',verified_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',local.id);if(remote.status==='succeeded'){const {data,error}=await service.rpc('process_verified_yookassa_test_refund',{p_refund_id:local.id,p_external_refund_id:remote.id,p_provider_status:remote.status,p_provider_payload:safe,p_actor_user_id:actor});if(error)throw new Error(`refund_ledger_apply_failed:${error.message}`);return data;}if(remote.status==='canceled')await audit(actor,'refund.yookassa_test_canceled','refund',local.id,'Verified canceled refund against YooKassa API',{external_refund_id:remote.id,payment_id:local.payment_id,test_mode:true,cancellation_details:remote?.cancellation_details||null});return null;}

Deno.serve(async(req)=>{
 const origin=req.headers.get('origin');if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(origin)});if(req.method!=='POST')return json(405,{ok:false,error:'method_not_allowed'},origin);if(origin&&!ORIGINS.has(origin))return json(403,{ok:false,error:'origin_not_allowed'},origin);
 const token=(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,'');if(!token)return json(401,{ok:false,error:'auth_required'},origin);const {data:u,error:ue}=await service.auth.getUser(token);const user=u?.user;if(ue||!user)return json(401,{ok:false,error:'invalid_session'},origin);const {data:profile}=await service.from('profiles').select('role,status').eq('id',user.id).maybeSingle();if(!profile||profile.status!=='active'||!ROLES.has(profile.role))return json(403,{ok:false,error:'finance_or_admin_required'},origin);
 let body:any={};try{body=await req.json()}catch{return json(400,{ok:false,error:'invalid_json'},origin)}const action=String(body?.action||'');if(action==='config_status')return json(200,{ok:true,configured:Boolean(SHOP_ID&&SECRET),mode:'YOOKASSA_TEST_REFUND',live_money:false},origin);if(!SHOP_ID||!SECRET)return json(409,{ok:false,error:'yookassa_test_credentials_missing'},origin);

 if(action==='create_full'){
   const orderId=String(body?.order_id||'');if(!orderId)return json(400,{ok:false,error:'order_id_required'},origin);const {data:payment}=await service.from('payments').select('id,order_id,provider,external_payment_id,amount,currency,canonical_status,test_mode').eq('order_id',orderId).eq('provider','yookassa_test').eq('test_mode',true).order('created_at',{ascending:false}).limit(1).maybeSingle();if(!payment)return json(404,{ok:false,error:'yookassa_test_payment_not_found'},origin);if(!['succeeded','partially_refunded'].includes(payment.canonical_status))return json(409,{ok:false,error:'payment_not_refundable',status:payment.canonical_status},origin);
   const remotePayment=await paymentGet(payment.external_payment_id);if(remotePayment?.test!==true||remotePayment?.status!=='succeeded')return json(409,{ok:false,error:'provider_payment_not_refundable',provider_status:remotePayment?.status||null},origin);const {data:controls}=await service.from('system_controls').select('test_refunds_enabled,max_test_refund').eq('id',1).single();if(!controls?.test_refunds_enabled)return json(409,{ok:false,error:'test_refunds_disabled'},origin);const {data:done}=await service.from('refunds').select('amount').eq('payment_id',payment.id).eq('status','succeeded');const already=(done||[]).reduce((s:any,r:any)=>s+Number(r.amount),0);const remaining=Number(payment.amount)-already;if(remaining<=0)return json(409,{ok:false,error:'payment_already_fully_refunded'},origin);if(remaining>Number(controls.max_test_refund))return json(409,{ok:false,error:'test_refund_limit_exceeded',remaining,max:Number(controls.max_test_refund)},origin);
   const idem=`yktest-refund:full:${payment.id}`.slice(0,64);let {data:local}=await service.from('refunds').select('*').eq('idempotency_key',idem).maybeSingle();if(!local){const ins=await service.from('refunds').insert({payment_id:payment.id,amount:remaining,currency:payment.currency,status:'processing',reason:'YooKassa TEST full refund acceptance',requested_by:user.id,approved_by:user.id,provider:'yookassa_test',provider_status:'creating',provider_payload:{},idempotency_key:idem,test_mode:true}).select('*').single();if(ins.error)return json(500,{ok:false,error:'local_refund_create_failed',detail:ins.error.message},origin);local=ins.data;}
   if(local.external_refund_id){const remote=await refundGet(local.external_refund_id);const applied=await applyRefund({...local,payment_external_id:payment.external_payment_id},remote,user.id);return json(200,{ok:true,refund:{id:local.id,external_refund_id:remote.id,status:remote.status,amount:remote.amount},applied,idempotent:true,live_money:false},origin)}
   const payload={payment_id:payment.external_payment_id,amount:{value:remaining.toFixed(2),currency:payment.currency},description:'TEST refund Station order',metadata:{station_order_id:orderId,station_payment_id:payment.id,station_test:'true'}};const rr=await fetch('https://api.yookassa.ru/v3/refunds',{method:'POST',headers:{Authorization:authHeader(),'Idempotence-Key':idem,'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify(payload)});const remote=await rr.json().catch(()=>({}));if(!rr.ok)return json(502,{ok:false,error:'yookassa_refund_create_failed',provider_status:rr.status,provider_error:remote?.description||remote?.type||'api_error'},origin);
   const safe=safeRefund(remote);await service.from('refunds').update({external_refund_id:remote.id,provider_status:remote.status,provider_payload:safe,status:remote.status==='succeeded'?'succeeded':remote.status==='canceled'?'canceled':'processing',updated_at:new Date().toISOString()}).eq('id',local.id);local={...local,external_refund_id:remote.id,payment_external_id:payment.external_payment_id};await audit(user.id,'refund.yookassa_test_created','refund',local.id,'Created full refund via YooKassa TEST API',{order_id:orderId,payment_id:payment.id,external_payment_id:payment.external_payment_id,external_refund_id:remote.id,amount:remaining,currency:payment.currency,test_mode:true});let applied=null;if(remote.status==='succeeded')applied=await applyRefund(local,remote,user.id);return json(201,{ok:true,refund:{id:local.id,external_refund_id:remote.id,status:remote.status,amount:remote.amount},applied,live_money:false},origin);
 }
 if(action==='refresh'){const refundId=String(body?.refund_id||'');if(!refundId)return json(400,{ok:false,error:'refund_id_required'},origin);const {data:r}=await service.from('refunds').select('*,payments(external_payment_id)').eq('id',refundId).eq('provider','yookassa_test').eq('test_mode',true).maybeSingle();if(!r||!r.external_refund_id)return json(404,{ok:false,error:'refund_not_found'},origin);const remote=await refundGet(r.external_refund_id);const applied=await applyRefund({...r,payment_external_id:r.payments?.external_payment_id},remote,user.id);return json(200,{ok:true,refund:{id:r.id,external_refund_id:remote.id,status:remote.status,amount:remote.amount},applied,live_money:false},origin)}
 if(action==='list_for_order'){const orderId=String(body?.order_id||'');const {data:pays}=await service.from('payments').select('id').eq('order_id',orderId);const ids=(pays||[]).map((p:any)=>p.id);if(!ids.length)return json(200,{ok:true,refunds:[]},origin);const {data:rows}=await service.from('refunds').select('id,payment_id,amount,currency,status,provider,provider_status,external_refund_id,test_mode,created_at,updated_at').in('payment_id',ids).order('created_at',{ascending:false});return json(200,{ok:true,refunds:rows||[]},origin)}
 return json(400,{ok:false,error:'unknown_action'},origin);
});