import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const URL='https://xwapzjsnqyfiqbzeycyh.supabase.co';
const KEY='sb_publishable_mVOY1vbk6e6jiBnT0VAX9w_sFXODDsi';
const sb=createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let snapshot=null,currentChannel=null,pollTimer=null;
async function api(action,payload={}){const {data,error}=await sb.functions.invoke('business-network',{body:{action,...payload}});if(error){let m=error.message;try{if(error.context){const j=await error.context.json();m=j.error+(j.detail?`: ${j.detail}`:'')}}catch{}throw new Error(m)}if(!data?.ok)throw new Error(data?.error||'business_network_error');return data}
function href(v,type='url'){const s=String(v||'').trim();if(!s)return null;if(type==='phone')return `tel:${s.replace(/[^+0-9]/g,'')}`;if(type==='email')return `mailto:${s}`;if(/^https?:\/\//i.test(s))return s;if(type==='telegram')return `https://t.me/${s.replace(/^@/,'')}`;return `https://${s.replace(/^\/+/, '')}`}
function tags(xs,kind=''){return (xs||[]).map(x=>`<span class="tag ${kind}">${esc(x)}</span>`).join('')}
function contacts(p){const parts=[];if(p.contact_person)parts.push(`<span>👤 ${esc(p.contact_person)}</span>`);if(p.public_phone)parts.push(`<a href="${esc(href(p.public_phone,'phone'))}">☎ ${esc(p.public_phone)}</a>`);if(p.public_email)parts.push(`<a href="${esc(href(p.public_email,'email'))}">✉ ${esc(p.public_email)}</a>`);if(p.telegram)parts.push(`<a target="_blank" rel="noopener" href="${esc(href(p.telegram,'telegram'))}">Telegram</a>`);if(p.max_contact)parts.push(`<span>MAX: ${esc(p.max_contact)}</span>`);if(p.website)parts.push(`<a target="_blank" rel="noopener" href="${esc(href(p.website))}">${esc(p.website)}</a>`);return parts.length?parts.join(''):'<span>Контакты пока не опубликованы</span>'}
function renderDirectory(){const items=snapshot?.directory||[];$('#directory').innerHTML=items.length?items.map(p=>`<article class="company-card"><div class="meta">${esc(p.city||'')} · ${esc(p.vertical_code||'BUSINESS').toUpperCase()}</div><h3>${esc(p.display_name||p.company_name)}</h3>${p.headline?`<strong>${esc(p.headline)}</strong>`:''}${p.about?`<p>${esc(p.about)}</p>`:''}${p.offers?.length?`<small class="meta">МОЖЕМ ПРЕДЛОЖИТЬ</small><div class="tags">${tags(p.offers)}</div>`:''}${p.needs?.length?`<small class="meta">ИЩЕМ / НУЖНО</small><div class="tags">${tags(p.needs,'need')}</div>`:''}<div class="contacts">${contacts(p)}</div></article>`).join(''):'<div class="empty-network">В каталоге пока нет опубликованных визиток. Первая компания может заполнить карточку в разделе «Моя карточка».</div>'}
function channelCanPost(c,w){if(!w)return false;const r=w.access_role;if(c.scope==='all_business')return true;if(c.scope==='owners')return r==='owner';if(c.scope==='managers')return r==='owner'||r==='manager';if(c.scope==='vertical')return w.vertical_code===c.vertical_code;return false}
function renderChannels(){const cs=snapshot?.channels||[];$('#channels').innerHTML=cs.map(c=>`<button data-code="${esc(c.code)}" title="${esc(c.description_ru||'')}">${esc(c.name_ru)}</button>`).join('');document.querySelectorAll('#channels button').forEach(b=>b.onclick=()=>openChannel(b.dataset.code));if(cs.length)openChannel(cs[0].code)}
async function openChannel(code){const c=(snapshot.channels||[]).find(x=>x.code===code);if(!c)return;currentChannel=c;document.querySelectorAll('#channels button').forEach(b=>b.classList.toggle('active',b.dataset.code===code));$('#chatTitle').textContent=c.name_ru;const allowed=(snapshot.my_workspaces||[]).filter(w=>channelCanPost(c,w));$('#postAs').innerHTML=allowed.map(w=>`<option value="${w.id}">${esc(w.name)} · ${esc(w.access_role)}</option>`).join('');$('#messageText').disabled=!allowed.length;$('#messageForm button').disabled=!allowed.length;await loadMessages()}
async function loadMessages(){if(!currentChannel)return;try{const x=await api('messages',{channel_code:currentChannel.code,limit:80});const m=x.messages||[];$('#messages').innerHTML=m.length?m.map(v=>`<div class="message"><div><span class="who">${esc(v.author_name||'Пользователь')} · ${esc(v.company?.name||'Компания')}</span><span class="when">${new Date(v.created_at).toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</span></div><p>${esc(v.body)}</p></div>`).join(''):'<div class="empty-network">Сообщений пока нет. Можно начать с полезного знакомства: кто вы, что делаете и чем можете быть полезны другим.</div>';$('#messages').scrollTop=$('#messages').scrollHeight}catch(e){$('#messages').innerHTML=`<div class="empty-network">Не удалось загрузить чат: ${esc(e.message)}</div>`}}
function ownProfile(workspaceId){return (snapshot?.my_profiles||[]).find(p=>p.workspace_id===workspaceId)||{workspace_id:workspaceId,discoverable:true,offers:[],needs:[]}}
function fillProfile(){const id=$('#profileWorkspace').value;if(!id)return;const w=(snapshot.my_workspaces||[]).find(x=>x.id===id),p=ownProfile(id);$('#headline').value=p.headline||'';$('#about').value=p.about||'';$('#offers').value=(p.offers||[]).join(', ');$('#needs').value=(p.needs||[]).join(', ');$('#contactPerson').value=p.contact_person||'';$('#publicPhone').value=p.public_phone||'';$('#publicEmail').value=p.public_email||'';$('#telegram').value=p.telegram||'';$('#maxContact').value=p.max_contact||'';$('#website').value=p.website||'';$('#discoverable').checked=p.discoverable!==false;$('#discoverable').disabled=w?.access_role!=='owner'}
function renderProfileEditor(){const ws=(snapshot?.my_workspaces||[]).filter(w=>['owner','manager'].includes(w.access_role));$('#profileWorkspace').innerHTML=ws.map(w=>`<option value="${w.id}">${esc(w.name)} · ${esc(w.access_role)}</option>`).join('');$('#profileForm').querySelectorAll('input,textarea,button,select').forEach(x=>x.disabled=!ws.length);if(ws.length){$('#profileWorkspace').disabled=false;fillProfile()}else{$('#profileMsg').textContent=snapshot?.platform_role?'Администратор Station видит сеть, но публичную визитку редактирует владелец или менеджер компании.':'Для редактирования визитки нужна роль владельца или менеджера.'}}
async function load(){snapshot=await api('snapshot');$('#companyCount').textContent=Number(snapshot.company_count||0).toLocaleString('ru-RU');renderDirectory();renderChannels();renderProfileEditor()}
function showTab(name){document.querySelectorAll('.network-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));$('#directoryTab').hidden=name!=='directory';$('#chatTab').hidden=name!=='chat';$('#profileTab').hidden=name!=='profile';if(name==='chat')loadMessages()}
document.querySelectorAll('.network-tabs button').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
$('#messageForm').onsubmit=async e=>{e.preventDefault();if(!currentChannel)return;const body=$('#messageText').value.trim(),workspace_id=$('#postAs').value;if(!body||!workspace_id)return;const btn=e.submitter;btn.disabled=true;try{await api('post_message',{channel_code:currentChannel.code,workspace_id,body});$('#messageText').value='';await loadMessages()}catch(err){alert(err.message)}finally{btn.disabled=false}};
$('#profileWorkspace').onchange=fillProfile;
$('#profileForm').onsubmit=async e=>{e.preventDefault();const workspace_id=$('#profileWorkspace').value,w=(snapshot.my_workspaces||[]).find(x=>x.id===workspace_id);if(!workspace_id)return;const payload={workspace_id,headline:$('#headline').value,about:$('#about').value,offers:$('#offers').value.split(',').map(x=>x.trim()).filter(Boolean),needs:$('#needs').value.split(',').map(x=>x.trim()).filter(Boolean),contact_person:$('#contactPerson').value,public_phone:$('#publicPhone').value,public_email:$('#publicEmail').value,telegram:$('#telegram').value,max_contact:$('#maxContact').value,website:$('#website').value};if(w?.access_role==='owner'){payload.discoverable=$('#discoverable').checked;payload.contacts_visibility='members'}$('#profileMsg').textContent='Сохраняем…';try{await api('update_profile',payload);$('#profileMsg').textContent='Визитка сохранена.';await load()}catch(err){$('#profileMsg').textContent=err.message}};
$('#authForm').onsubmit=async e=>{e.preventDefault();$('#authMsg').textContent='Вход…';const {error}=await sb.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});$('#authMsg').textContent=error?error.message:'';if(!error)boot()};
$('#signOut').onclick=async()=>{await sb.auth.signOut();location.reload()};
async function boot(){const {data:{session}}=await sb.auth.getSession();if(!session){$('#authPanel').hidden=false;$('#networkApp').hidden=true;return}$('#authPanel').hidden=true;$('#networkApp').hidden=false;$('#identity').textContent=session.user.email||'ONLINE';try{await load()}catch(e){$('#networkApp').hidden=true;$('#authPanel').hidden=false;$('#authMsg').textContent=e.message}}
sb.auth.onAuthStateChange(()=>setTimeout(boot,150));pollTimer=setInterval(()=>{if(currentChannel&&!$('#chatTab').hidden&&!document.hidden)loadMessages()},8000);boot();