import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';

const SUPABASE_URL='https://xwapzjsnqyfiqbzeycyh.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_mVOY1vbk6e6jiBnT0VAX9w_sFXODDsi';
const sb=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ACTIVE=new Set(['PLANNED','CODING','QA','BUILD']);
let snapshot={agents:[],projects:[],gates:[],events:[],assistant_queue:[],checkpoints:[]};
let currentFilter='all',currentDoc='handoff_md',timer=null,currentProject=null,currentSubtasks=[];

async function invoke(action,payload={}){const {data,error}=await sb.functions.invoke('my-bay-control',{body:{action,...payload}});if(error){let detail=error.message;try{if(error.context){const j=await error.context.json();detail=j.error+(j.detail?`: ${j.detail}`:'')}}catch{}throw new Error(detail)}if(!data?.ok)throw new Error(data?.error||'my_bay_error');return data}

async function invokeFunction(name,body){const {data,error}=await sb.functions.invoke(name,{body});if(error){let detail=error.message;try{if(error.context){const j=await error.context.json();detail=j.error+(j.detail?`: ${j.detail}`:'')}}catch{}throw new Error(detail)}if(!data?.ok)throw new Error(data?.error||`${name}_error`);return data}
async function loadIntegrations(){try{const [sec,tg]=await Promise.all([invokeFunction('devfactory-secrets',{action:'list'}),invokeFunction('devfactory-telegram-control',{action:'status'})]);renderSecrets(sec.secrets||[]);renderTelegram(tg)}catch(e){console.error('integration status',e)}}
function renderSecrets(items){const box=$('#secretList');if(!box)return;box.innerHTML='';for(const x of items){const row=document.createElement('article');row.className='secret-card';row.innerHTML=`<b>${esc(x.service)}.${esc(x.secret_key)}</b><span class="badge ${x.status==='READY'?'state-ready':'state-human'}">${esc(x.status)}</span><small>${esc(x.purpose||x.scope||'')} ${x.fingerprint?'· '+esc(x.fingerprint):''}</small>`;box.append(row)}if(!items.length)box.innerHTML='<div class="empty">Реестр секретов пуст.</div>'}
function renderTelegram(tg){const box=$('#telegramStatus');if(!box)return;const bot=(tg.secrets||[]).find(x=>x.secret_key==='bot_token');const general=(tg.destinations||[]).find(x=>x.kind==='general'&&x.status==='active');const owner=(tg.links||[]).find(x=>x.role==='owner'&&x.status==='active');box.innerHTML=`<article class="secret-card"><b>Bot token</b><span class="badge ${bot?.status==='READY'?'state-ready':'state-human'}">${esc(bot?.status||'MISSING')}</span></article><article class="secret-card"><b>Владелец</b><span>${owner?'ПРИВЯЗАН':'НЕ ПРИВЯЗАН'}</span></article><article class="secret-card"><b>Общий канал</b><span>${esc(general?.title||'НЕ НАЗНАЧЕН')}</span></article>`}
const fmt=d=>d?new Date(d).toLocaleString():'—';
const ago=d=>!d?Infinity:(Date.now()-new Date(d).getTime())/1000;
function stateClass(s){if(s==='READY')return'state-ready';if(s==='FAILED'||s==='CANCELED')return'state-failed';if(s==='HUMAN_GATE')return'state-human';if(ACTIVE.has(s)||s==='NEW')return'state-active';return''}
function progressIndex(s){return {NEW:0,PLANNED:0,CODING:1,QA:2,BUILD:3,READY:5}[s]??0}
function actionButton(text,cls,fn){const b=document.createElement('button');b.className=cls;b.textContent=text;b.onclick=async()=>{b.disabled=true;try{await fn()}finally{b.disabled=false}};return b}
async function boot(){const {data:{session}}=await sb.auth.getSession();if(!session){$('#identity').textContent='OFFLINE';$('#accessText').textContent='Сначала войди через операторский пульт — сессия автоматически подхватится здесь.';$('#loginLink').hidden=false;return}try{const who=await invoke('whoami');$('#identity').textContent=`${who.user?.display_name||'DIMA'} · ${who.user?.role||''}`;if(!who.authorized){$('#accessText').textContent='Для «Моего отсека» нужна роль operator или admin.';return}$('#accessPanel').hidden=true;$('#app').hidden=false;await refresh();await loadIntegrations();timer=setInterval(()=>refresh(false),12000)}catch(e){$('#accessText').textContent=`Не удалось открыть отсек: ${e.message}`}}
async function refresh(showError=true){try{snapshot=await invoke('dashboard');renderAll();if(currentProject)await refreshOpenProject()}catch(e){if(showError)alert(e.message);$('#agentState').textContent='ERROR';$('#agentState').className='agent-offline';$('#agentMeta').textContent=e.message}}
function renderAll(){renderStats();renderAssistant();renderProjects();renderOverview();renderGates()}
function renderStats(){
  const a=(snapshot.agents||[])[0],fresh=a&&ago(a.heartbeat_at)<45,state=fresh?(a.status==='busy'?'BUSY':'ONLINE'):'OFFLINE';
  $('#agentState').textContent=state;$('#agentState').className=fresh?(a.status==='busy'?'agent-busy':'agent-online'):'agent-offline';
  $('#agentMeta').textContent=a?`${a.name} · ${a.version||'version ?'} · ${fmt(a.heartbeat_at)}`:'Агент ещё не зарегистрирован';
  const s=snapshot.assistant_state,q=snapshot.assistant_queue||[];
  $('#assistantState').textContent=s?.mode==='autonomous'?'ACTIVE':'WAITING';$('#assistantState').className=s?.mode==='autonomous'?'agent-online':'agent-busy';
  $('#assistantMeta').textContent=s?`event #${s.last_event_id||0} · ${fmt(s.updated_at)}`:'Нет состояния';
  const ps=snapshot.projects||[],g=snapshot.gates||[];$('#activeCount').textContent=ps.filter(p=>ACTIVE.has(p.state)).length;$('#readyCount').textContent=ps.filter(p=>p.state==='READY').length;$('#gateCount').textContent=g.length;$('#gateTabCount').textContent=g.length;$('#assistantQueueBadge').textContent=`QUEUE ${q.length}`;
}
function renderAssistant(){
  const s=snapshot.assistant_state||{},q=snapshot.assistant_queue||[],cp=(snapshot.checkpoints||[])[0];
  $('#assistantObjective').textContent=s.current_objective||'—';$('#assistantCheckpoint').textContent=cp?`${fmt(cp.created_at)} · ${cp.metadata?.state||cp.session_key}`:'—';$('#assistantEvent').textContent=`#${s.last_event_id||0}`;$('#canonicalDoc').textContent=s[currentDoc]||'Документ ещё не сформирован.';
  const box=$('#assistantQueue');box.innerHTML='';if(!q.length){box.innerHTML='<div class="empty">Очередь пуста — диспетчеру сейчас нечего разбирать.</div>';return}
  for(const item of q.slice(0,40)){const row=document.createElement('div');row.className='queue-item';row.innerHTML=`<span class="badge">P${esc(item.priority)}</span><div><b>${esc(item.subject)}</b><small>${esc(item.kind)} · ${fmt(item.created_at)}</small></div><span class="queue-source">${esc(item.source||'')}</span>`;box.append(row)}
}
function visibleProjects(){const ps=snapshot.projects||[];if(currentFilter==='active')return ps.filter(p=>ACTIVE.has(p.state)||['NEW','PLANNED'].includes(p.state));if(currentFilter==='attention')return ps.filter(p=>p.state==='HUMAN_GATE'||p.state==='FAILED');if(currentFilter==='done')return ps.filter(p=>p.state==='READY');return ps}
function projectCard(p,compact=false){
  const card=document.createElement('article');card.className='card project-card'+(compact?' compact-card':'');
  const idx=progressIndex(p.state),progress=[0,1,2,3,4].map(i=>`<i class="${i<idx?'done':''}"></i>`).join('');
  const artifact=p.artifact_ref?.startsWith('storage:')?'<div class="meta state-ready">Результат в облаке</div>':(p.artifact_ref?'<div class="meta">Артефакт готовится…</div>':'');
  card.innerHTML=`<div class="project-title"><div><h3>${esc(p.name)}</h3><div class="meta">${fmt(p.created_at)} · попытка ${esc(p.attempts)}/${esc(p.max_attempts)}</div></div><span class="badge ${stateClass(p.state)}">${esc(p.state)}</span></div><p class="goal">${esc(p.goal)}</p><div class="progress-line">${progress}</div>${p.last_error?`<div class="meta state-failed">${esc(p.last_error)}</div>`:''}${artifact}<div class="small-actions"></div>`;
  const actions=card.querySelector('.small-actions');if(!compact){if(ACTIVE.has(p.state))actions.append(actionButton('Пауза','ghost',()=>queueCommand(p.id,'pause')));if(p.state==='PAUSED')actions.append(actionButton('Продолжить','primary',()=>queueCommand(p.id,'resume')));if(p.state==='FAILED')actions.append(actionButton('Повторить','primary',()=>queueCommand(p.id,'retry')));if(p.state==='READY'&&p.artifact_ref?.startsWith('storage:'))actions.append(actionButton('Скачать','primary',()=>downloadArtifact(p.id)));if(!['READY','CANCELED'].includes(p.state))actions.append(actionButton('Отменить','danger',()=>queueCommand(p.id,'cancel')))}
  for(const b of actions.children)b.addEventListener('click',e=>e.stopPropagation());card.addEventListener('click',()=>openProject(p.id));return card
}
function renderProjects(){const box=$('#projects'),items=visibleProjects();box.innerHTML='';if(!items.length){box.innerHTML='<div class="empty">Здесь пока пусто.</div>';return}for(const p of items)box.append(projectCard(p))}
function renderOverview(){const box=$('#overviewProjects'),items=(snapshot.projects||[]).filter(p=>ACTIVE.has(p.state)||['NEW','PLANNED','HUMAN_GATE'].includes(p.state)).slice(0,6);box.innerHTML='';if(!items.length){box.innerHTML='<div class="empty">Активных проектов сейчас нет.</div>';return}for(const p of items)box.append(projectCard(p,true))}
async function queueCommand(projectId,command,payload={}){if(command==='cancel'&&!confirm('Отменить проект?'))return;try{await invoke('command',{project_id:projectId,command,payload});await refresh()}catch(e){alert(e.message)}}
async function downloadArtifact(projectId){const tab=window.open('about:blank','_blank');try{const d=await invoke('artifact_url',{project_id:projectId});if(tab)tab.location=d.url;else location.href=d.url}catch(e){if(tab)tab.close();alert(`Не удалось получить файл: ${e.message}`)}}
function renderGates(){
  const box=$('#gates'),items=snapshot.gates||[];box.innerHTML='';if(!items.length){box.innerHTML='<div class="empty">Ничего не ждёт твоего подтверждения.</div>';return}
  for(const g of items){const p=(snapshot.projects||[]).find(x=>x.id===g.project_id);const card=document.createElement('article');card.className='card';card.innerHTML=`<div class="card-head"><div><h3>${esc(p?.name||'Проект')}</h3><div class="meta">${fmt(g.requested_at)} · ${esc(g.gate_type)}</div></div><span class="badge state-human">НУЖЕН ТЫ</span></div><p class="statement">${esc(g.reason)}</p><div class="actions"></div>`;card.querySelector('.actions').append(actionButton('Подтвердил — продолжить','primary',async()=>{await invoke('command',{project_id:g.project_id,command:'approve_gate',gate_id:g.id});await refresh()}));box.append(card)}
}
async function loadSubtasks(projectId){const {data,error}=await sb.from('devfactory_subtasks').select('*').eq('project_id',projectId).order('sort_order').order('created_at');if(error)throw error;currentSubtasks=data||[];return currentSubtasks}
function renderSubtasks(){
  const box=$('#subtasks');box.innerHTML='';$('#subtaskCount').textContent=currentSubtasks.length;
  if(!currentSubtasks.length){box.innerHTML='<div class="empty">Подзадач пока нет.</div>';return}
  const byParent=new Map();for(const t of currentSubtasks){const k=t.parent_id||'root';if(!byParent.has(k))byParent.set(k,[]);byParent.get(k).push(t)}
  const draw=(parent,depth=0)=>{for(const t of byParent.get(parent)||[]){const row=document.createElement('div');row.className=`subtask-row depth-${Math.min(depth,3)}`;row.innerHTML=`<button class="subtask-state ${esc(t.status.toLowerCase())}">${esc(t.status)}</button><div><b>${esc(t.title)}</b>${t.details?`<small>${esc(t.details)}</small>`:''}</div><div class="subtask-actions"></div>`;const acts=row.querySelector('.subtask-actions');acts.append(actionButton('+ дочерняя','ghost',()=>addChildSubtask(t.id)));acts.append(actionButton('×','ghost',()=>deleteSubtask(t.id)));row.querySelector('.subtask-state').onclick=()=>cycleSubtask(t);box.append(row);draw(t.id,depth+1)}};draw('root')
}
async function addSubtask(title,parentId=null){if(!currentProject||!title.trim())return;const max=Math.max(0,...currentSubtasks.map(x=>Number(x.sort_order)||0));const {error}=await sb.from('devfactory_subtasks').insert({project_id:currentProject.id,parent_id:parentId,title:title.trim(),sort_order:max+10,source:'manual'});if(error)throw error;await refreshOpenProject()}
async function addChildSubtask(parentId){const title=prompt('Название дочерней подзадачи');if(title)await addSubtask(title,parentId)}
async function cycleSubtask(t){const next={TODO:'DOING',DOING:'DONE',DONE:'TODO',BLOCKED:'DOING',CANCELED:'TODO'}[t.status]||'TODO';const {error}=await sb.from('devfactory_subtasks').update({status:next,updated_at:new Date().toISOString()}).eq('id',t.id);if(error)alert(error.message);else await refreshOpenProject()}
async function deleteSubtask(id){if(!confirm('Удалить эту подзадачу и её дочерние?'))return;const {error}=await sb.from('devfactory_subtasks').delete().eq('id',id);if(error)alert(error.message);else await refreshOpenProject()}
async function openProject(id){try{const d=await invoke('project',{project_id:id});currentProject=d.project;await loadSubtasks(id);renderProjectDetail(d);$('#detailPanel').hidden=false;$('#detailPanel').scrollIntoView({behavior:'smooth',block:'start'})}catch(e){alert(e.message)}}
async function refreshOpenProject(){if(!currentProject)return;try{const d=await invoke('project',{project_id:currentProject.id});currentProject=d.project;await loadSubtasks(currentProject.id);renderProjectDetail(d)}catch(e){console.error(e)}}
function renderProjectDetail(d){
  const p=d.project;$('#detailTitle').textContent=p.name;$('#detailGoal').textContent=p.goal;$('#detailSummary').innerHTML=`<div><small>STATE</small><b class="${stateClass(p.state)}">${esc(p.state)}</b></div><div><small>ATTEMPTS</small><b>${esc(p.attempts)} / ${esc(p.max_attempts)}</b></div><div><small>WORKER</small><b>${esc(p.worker)}</b></div><div><small>UPDATED</small><b>${fmt(p.updated_at)}</b></div>`;
  const dl=$('#downloadArtifact');dl.hidden=!(p.state==='READY'&&p.artifact_ref?.startsWith('storage:'));renderSubtasks();
  const eb=$('#detailEvents');eb.innerHTML='';for(const e of d.events||[]){const row=document.createElement('div');row.className='event';row.innerHTML=`<time>${fmt(e.created_at)}</time><b>${esc(e.event_type)}</b><span>${esc(e.message||JSON.stringify(e.payload||{}))}</span>`;eb.append(row)}if(!(d.events||[]).length)eb.innerHTML='<div class="empty">Событий пока нет.</div>';
  const files=$('#detailFiles');files.innerHTML=p.artifact_ref?`<article class="file-card"><b>${p.artifact_ref.startsWith('storage:')?'Release artifact':'Artifact'}</b><code>${esc(p.artifact_ref)}</code><pre>${esc(JSON.stringify(p.artifact_metadata||{},null,2))}</pre>${p.artifact_ref.startsWith('storage:')?'<button class="primary" id="fileDownload">Скачать результат</button>':''}</article>`:'<div class="empty">Файлы появятся после сборки.</div>';const fd=$('#fileDownload');if(fd)fd.onclick=()=>downloadArtifact(p.id)
}
function showBayPanel(name){$$('.bay-tab').forEach(b=>b.classList.toggle('active',b.dataset.panel===name));$$('.bay-panel').forEach(p=>p.classList.toggle('active',p.dataset.bayPanel===name));}
function showProjectPanel(name){$$('.project-tab').forEach(b=>b.classList.toggle('active',b.dataset.projectPanel===name));$$('.project-panel').forEach(p=>p.classList.toggle('active',p.dataset.projectPanelContent===name));}
$('#newProjectForm').addEventListener('submit',async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;$('#createStatus').textContent='Ставлю в очередь…';try{const d=await invoke('create_project',{name:$('#projectName').value.trim(),goal:$('#projectGoal').value.trim(),priority:Number($('#projectPriority').value),max_attempts:Number($('#projectAttempts').value)});$('#createStatus').textContent=`Проект создан: ${d.project.state}`;e.target.reset();$('#projectPriority').value='100';$('#projectAttempts').value='4';await refresh();await openProject(d.project.id)}catch(err){$('#createStatus').textContent=err.message}finally{btn.disabled=false}});
$('#subtaskForm').addEventListener('submit',async e=>{e.preventDefault();const title=$('#subtaskTitle').value.trim();if(!title)return;try{await addSubtask(title);$('#subtaskTitle').value=''}catch(err){alert(err.message)}});
$('#secretForm').addEventListener('submit',async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;$('#secretStatus').textContent='Сохраняю…';try{await invokeFunction('devfactory-secrets',{action:'put',service:$('#secretService').value.trim(),secret_key:$('#secretKey').value.trim(),secret:$('#secretValue').value,purpose:'DIMA.OS runtime credential',scope:'cloud',rotation_days:90});$('#secretValue').value='';$('#secretStatus').textContent='Сохранено в Vault';if($('#secretService').value.trim().toLowerCase()==='telegram'&&$('#secretKey').value.trim().toLowerCase()==='bot_token'){try{await invokeFunction('devfactory-telegram-control',{action:'set_webhook'});$('#secretStatus').textContent='Сохранено в Vault · webhook установлен'}catch(w){$('#secretStatus').textContent='Сохранено в Vault · webhook: '+w.message}}await loadIntegrations()}catch(err){$('#secretStatus').textContent=err.message}finally{btn.disabled=false}});
$('#tgPair').onclick=async()=>{try{const d=await invokeFunction('devfactory-telegram-control',{action:'pair_code'});$('#tgPairCode').textContent=`Открой бота в Telegram и отправь:
/start ${d.code}

Код действует 15 минут. После привязки добавь бота в общий чат и отправь там /general.`}catch(e){alert(e.message)}};
$('#tgWebhook').onclick=async()=>{try{await invokeFunction('devfactory-telegram-control',{action:'set_webhook'});$('#tgPairCode').textContent='Webhook установлен ✅';await loadIntegrations()}catch(e){alert(e.message)}};
$('#tgTest').onclick=async()=>{try{await invokeFunction('devfactory-telegram-control',{action:'test'});$('#tgPairCode').textContent='Тестовое сообщение отправлено ✅'}catch(e){alert(e.message)}};
$('#refreshAll').onclick=()=>refresh();$('#closeDetail').onclick=()=>{$('#detailPanel').hidden=true;currentProject=null;currentSubtasks=[]};$('#downloadArtifact').onclick=()=>currentProject&&downloadArtifact(currentProject.id);
$$('.bay-tab,.jump-tab').forEach(b=>b.addEventListener('click',()=>{showBayPanel(b.dataset.panel);if(['telegram','secrets'].includes(b.dataset.panel))loadIntegrations()}));
$$('.project-tab').forEach(b=>b.addEventListener('click',()=>showProjectPanel(b.dataset.projectPanel)));
$$('.filter').forEach(b=>b.addEventListener('click',()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentFilter=b.dataset.filter;renderProjects()}));
$$('.doc-tab').forEach(b=>b.addEventListener('click',()=>{$$('.doc-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentDoc=b.dataset.doc;renderAssistant()}));
window.addEventListener('beforeunload',()=>{if(timer)clearInterval(timer)});
boot();
