import {writeFile} from 'node:fs/promises';
const LIVE='https://stationforhumanity.com';
const join=LIVE+'/#join', factory=LIVE+'/factory/', constitution=LIVE+'/constitution.html';
const arrow='<span aria-hidden="true">→</span>';
const glyphs={people:'<circle cx="9" cy="7" r="3"/><circle cx="18" cy="8" r="2"/><path d="M3 21v-4a6 6 0 0 1 12 0v4M18 13a4 4 0 0 1 4 4v4"/>',infinity:'<path d="M12 12c-3-6-10-6-10 0s7 6 10 0 10-6 10 0-7 6-10 0Z"/>',leaf:'<path d="M4 20C-2 5 14 2 22 3c-1 15-7 20-18 17Zm0 0L16 9"/>',chart:'<path d="M4 21V13m8 8V7m8 14V2"/>',idea:'<path d="M8 18h8m-7 4h6M8 15c0-3-4-4-4-8a8 8 0 0 1 16 0c0 4-4 5-4 8Z"/>',document:'<path d="M5 2h10l4 4v16H5ZM14 2v6h5M8 12h8m-8 4h8"/>',gear:'<circle cx="12" cy="12" r="4"/><path d="m10 2-1 3-3 1-3-1-2 4 3 2v3l-2 2 2 4 3-1 3 2 1 2h4l1-3 3-1 3 1 2-4-3-2v-3l2-2-2-4-3 1-3-2-1-2Z"/>',code:'<path d="m8 5-6 7 6 7m8-14 6 7-6 7M14 2 10 22"/>',book:'<path d="M12 5C8 2 4 2 1 3v17c4-1 8 0 11 2 3-2 7-3 11-2V3c-3-1-7-1-11 2Zm0 0v17"/>',shield:'<path d="m12 2 9 4v6c0 5-5 9-9 11-4-2-9-6-9-11V6ZM7 12l3 3 7-7"/>',plane:'<path d="m2 15 9-5V3c0-3 3-3 3 0v7l9 5v3l-9-3v5l3 2H9l2-2v-5l-9 3Z"/>',globe:'<circle cx="12" cy="12" r="10"/><ellipse cx="12" cy="12" rx="4" ry="10"/><path d="M2 12h20"/>',tool:'<path d="m14 4 4 4 4-4a7 7 0 0 1-9 9l-8 9-4-4 9-8a7 7 0 0 1 4-9Z"/>',brain:'<path d="M12 3c-6-5-9 2-7 5-6 2-4 10 0 10 0 6 7 5 7 2V3Zm0 0c6-5 9 2 7 5 6 2 4 10 0 10 0 6-7 5-7 2M7 8l5 4m5-4-5 4"/>'};
const icon=(name)=>`<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${glyphs[name]||glyphs.idea}</svg>`;
const pic=(name,alt='',cls='',hero=false)=>`<picture class="${cls}"><source type="image/avif" srcset="art/${name}-640.avif 640w, art/${name}-1280.avif 1280w${hero?`, art/${name}-1774.avif 1774w`:''}" sizes="${hero?'100vw':'(max-width: 600px) 90vw, (max-width: 1000px) 45vw, 25vw'}"><img src="art/${name}-1280.webp" srcset="art/${name}-640.webp 640w, art/${name}-1280.webp 1280w${hero?`, art/${name}-1774.webp 1774w`:''}" sizes="${hero?'100vw':'(max-width: 600px) 90vw, (max-width: 1000px) 45vw, 25vw'}" width="${hero?1774:1280}" height="${hero?887:853}" alt="${alt}" ${hero?'fetchpriority="high"':'loading="lazy"'} decoding="async"></picture>`;
const btn=(href,label,gold=false)=>`<a class="button ${gold?'gold':''}" href="${href}">${label}${arrow}</a>`;
const brand=`<a class="brand" href="./index.html" aria-label="Station for Humanity — главная"><span class="brand-mark">SFH</span><span class="brand-name">STATION<br>FOR HUMANITY</span></a>`;
const nav=(story)=>`<a href="./index.html" ${!story?'aria-current="page"':''}>О проекте</a><a href="./story.html" ${story?'aria-current="page"':''}>История</a><a href="${LIVE}/#value">Система</a><a href="${LIVE}/#modules">Модули</a><a href="${constitution}">Конституция</a><a href="${join}">Присоединиться</a>`;
const header=(story)=>`<a class="skip" href="#main">К содержанию</a><header class="masthead"><div class="wrap header-inner">${brand}<nav id="navigation" aria-label="Основная навигация">${nav(story)}</nav><a class="nav-cta button" href="${join}">Стать частью мечты ${arrow}</a><button class="menu-toggle" data-menu-toggle aria-controls="navigation" aria-expanded="false" aria-label="Открыть меню"><span></span><span></span></button></div></header>`;
const values=`<div class="hero-values"><div>${icon('infinity')}<span>Больше,<br>чем просто проект</span></div><div>${icon('people')}<span>Глобальное<br>сообщество</span></div><div>${icon('chart')}<span>Реальные<br>действия</span></div><div>${icon('leaf')}<span>Устойчивое<br>будущее</span></div></div>`;
const footer=(story)=>`<footer class="footer"><div class="footer-landscape">${pic('story-hero','','footer-art',true)}<div class="wrap footer-main">${brand}<nav aria-label="Навигация в подвале">${nav(story)}</nav><a class="operator-link" href="${LIVE}/operator.html">Для операторов ${arrow}</a></div></div><div class="wrap footer-bottom"><span>© 2026 Station for Humanity</span><span class="eyebrow">ОДНА ПЛАНЕТА. ТЫСЯЧИ МЕЧТ.</span><span class="handwritten">Дальше — вместе. ♡</span></div></footer>`;
const head=(title)=>`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#031323"><meta name="robots" content="noindex,nofollow"><meta name="description" content="Люди, технологии и большие мечты. От первого шага к Station for Humanity."><title>${title} — Station for Humanity</title><link rel="icon" href="../assets/favicon.svg"><link rel="stylesheet" href="./styles.css"><script defer src="./app.js"></script></head><body>`;
const sectionHead=(eyebrow,title,href,label)=>`<div class="section-heading"><div><p class="eyebrow">${eyebrow}</p><h2>${title}</h2></div>${href?`<a class="text-link" href="${href}">${label} ${arrow}</a>`:''}</div>`;
const homeHero=`<section class="hero home-hero">${pic('home-hero','Люди перед горным озером, Землёй и будущей Dream Station. Художественный образ.','hero-art',true)}<div class="hero-shade"></div><div class="wrap hero-content"><p class="eyebrow">ЛЮДИ <span>×</span> ТЕХНОЛОГИИ <span>×</span> ЗНАНИЯ <span>×</span> РЕСУРСЫ</p><h1><span>STATION</span><strong>ДЛЯ ЧЕЛОВЕЧЕСТВА</strong></h1><p class="hero-copy">Мы объединяем людей, ИИ, машины, знания и ресурсы,<br class="desktop-break"> чтобы создавать ценность, которая возвращается<br class="desktop-break"> в жизнь — на Земле и за её пределами.</p><div class="actions">${btn(join,'Присоединиться к станции',true)}${btn(LIVE+'/#value','Изучить систему')}</div><p class="handwritten hero-note">Одна планета.<br>Тысячи мечт.<br>Больше возможностей. ♡</p>${values}</div></section>`;
const portals=[['dream','История большой мечты','От первого полёта до глобального сообщества. Как всё началось и куда мы идём.','./story.html'],['earth','Как работает система','От мечты человека к реальному результату. Прозрачный процесс, который объединяет всех.',LIVE+'/#value'],['station','Модули станции','Инфраструктура, где идеи становятся реальностью. Взаимосвязанные направления для людей и проектов.',LIVE+'/#modules'],['council','Конституция станции','Люди. Достоинство. Мечты. Технологии. Общая ответственность.',constitution],['people','Стань частью станции','Разные люди. Одна система. Найди своё место — с мечтой, навыками или ресурсами.',join]];
const portalSection=`<section class="section"><div class="wrap">${sectionHead('ИССЛЕДУЙТЕ НАПРАВЛЕНИЯ','Одна экосистема. Тысячи возможностей.','./story.html','Вместе мы создаём лучшее завтра.')}<div class="portals">${portals.map(([art,title,copy,href])=>`<a class="scene-card portal" href="${href}">${pic(art)}<div class="card-copy"><h3>${title}</h3><p>${copy}</p><span class="text-link">Подробнее ${arrow}</span></div></a>`).join('')}</div></div></section>`;
const process=[['idea','Мечта','У каждого начинается с мечты.'],['document','Заявка','Превращаем мечту в конкретную задачу.'],['people','Команда','Находим людей и ресурсы.'],['gear','Реализация','Создаём продукты и решения.'],['chart','Результат','Проверяем, что получилось.'],['infinity','Рост','Больше людей. Больше возможностей.']];
const processSection=`<section class="section"><div class="wrap">${sectionHead('КАК РАБОТАЕТ СИСТЕМА','От мечты — к реальному результату.',LIVE+'/#value','Простой путь. Большие изменения.')}<ol class="process">${process.map(([glyph,title,copy],i)=>`<li><span class="step-number">${i+1}</span>${icon(glyph)}<h3>${title}</h3><p>${copy}</p></li>`).join('')}</ol></div></section>`;
const modules=[['ai-lab','brain','AI DOCK','ИИ и агенты'],['ai-lab','code','DEVELOPER DOCK','Разработка'],['workshop','tool','MAKER DOCK','От идей к прототипам'],['factory','gear','INDUSTRY DOCK','Промышленность'],['council','book','KNOWLEDGE DOCK','Обучение и обмен знаниями'],['dream','leaf','IMPACT DOCK','Социальные проекты']];
const moduleSection=`<section class="section"><div class="wrap">${sectionHead('МОДУЛИ СТАНЦИИ','Инфраструктура для великих идей.',LIVE+'/#modules','Все модули')}<div class="modules">${modules.map(([art,glyph,title,copy])=>`<a class="scene-card module" href="${LIVE}/#modules">${pic(art)}<div class="module-copy">${icon(glyph)}<div><h3>${title}</h3><p>${copy}</p></div>${arrow}</div></a>`).join('')}</div></div></section>`;
const truthSection=`<section class="section"><div class="wrap">${sectionHead('ОТКРЫТО И ПРОВЕРЯЕМО','Реальные люди. Реальные действия.',factory,'Открыть Digital Factory')}<div class="truth-grid"><a class="truth-panel" href="${factory}">${pic('factory')}${icon('gear')}<div><h3>Digital Factory</h3><p>От задачи к рабочему продукту</p></div></a><a class="truth-panel" href="./story.html#first-step">${pic('flight')}${icon('plane')}<div><h3>Dream #000001</h3><p>Путь к мечте о полёте</p></div></a><a class="truth-panel" href="${constitution}">${pic('earth')}${icon('shield')}<div><h3>Article 0</h3><p>Возможности должны служить жизни.</p></div></a><a class="truth-panel" href="${join}">${pic('people')}${icon('people')}<div><h3>Founding Ticket</h3><p>Твой первый шаг на станцию</p></div></a></div></div></section>`;
const home=head('Главная')+header(false)+`<main id="main">${homeHero}${portalSection}${processSection}${moduleSection}${truthSection}</main>`+footer(false)+'</body></html>';
const stages=[
 ['dream','Мечта','Всё начинается с одной мечты','dream','С чего всё началось','Стать пилотом. Увидеть горы и озёра с другой высоты. Одна человеческая мечта стала отправной точкой: что, если технологии смогут приближать такие цели через полезную работу?'],
 ['first-step','Первый шаг','Превращаем цель в план','flight','Большой путь начинается с малого','Пробный полёт, медицинская комиссия, обучение, PPL(A), затем квалификация для полётов на гидросамолёте. Это этапы пути Dream #000001 — PILOT, а не отметки о выполнении.'],
 ['digital-factory','Digital Factory','Идеи становятся реальностью','factory','Сначала — реальная польза','Digital Factory создаёт цифровые продукты для реальных задач. Первый доступный продукт — SFH LeadBot: Telegram-бот для приёма заявок бизнеса. Конфигурация, цена и заказ остаются в действующей фабрике.'],
 ['dream-fund','Dream Fund','Полезная работа приближает мечту','fund','Ценность должна возвращаться людям','Dream Fund — часть замысла экономики станции. Распределение средств определяется утверждёнными правилами и подтверждёнными записями. Иллюстрация фонда не означает наличие денег или уже выполненных перечислений.'],
 ['first-result','Первый результат','Dream #000001 — PILOT','result','Первое доказательство должно быть настоящим','Первый кейс должен показать весь путь от полезной работы до достигнутой мечты. В публичном описании проекта этапы полётного пути пока обозначены как запланированные. Завершение требует проверяемых подтверждений.'],
 ['people','Другие люди и мечты','Сообщество, которое умножает добро','people','Большие мечты начинаются с человека','Мастерская, обучение, дом, ферма, лаборатория. Людям нужны разные возможности. Станция задумана как место, где встречаются потребности, знания, навыки, оборудование и полезная работа.'],
 ['global','Global Dream Factory','Люди + технологии + глобальная сеть','earth','Мечты не знают границ','Следующий горизонт — взаимосвязанная сеть людей и локальных фабрик. Обмен знаниями, сотрудничество и реальные проекты должны создавать больше возможностей для каждого. Это направление развития, а не заявление о готовой глобальной сети.'],
 ['station','Dream Station','Место, где мечты продолжаются','station','Следующая остановка — ещё больше возможностей','Dream Station — долгосрочный образ растущей станции для людей, ИИ, бизнеса и мечт. Мы начинаем с конкретных задач на Земле. Дальше — вместе.']
];
const storyHero=`<section class="hero story-hero">${pic('story-hero','Мечтатель у горного озера смотрит на Землю и будущую Dream Station. Художественный образ.','hero-art',true)}<div class="hero-shade"></div><div class="wrap hero-content"><p class="breadcrumb"><a href="./index.html">Главная</a><span>›</span>История большой мечты</p><h1>История большой мечты<strong>От шага к системе</strong></h1><p class="hero-copy">Мы превращаем мечты людей в реальные возможности —<br class="desktop-break"> через технологии, знания и глобальное сообщество.<br class="desktop-break"> От первого полёта до мировой Dream Station.</p><div class="actions">${btn(join,'Стать частью истории',true)}${btn('#dream','Читать историю')}</div><p class="handwritten hero-note">Одна планета.<br>Тысячи мечт.<br>Больше возможностей. ♡</p>${values}</div></section>`;
const timeline=`<section class="section timeline-section"><div class="wrap">${sectionHead('ПУТЬ БОЛЬШОЙ МЕЧТЫ','Путь от мечты к глобальной экосистеме', '#dream','Вся история в одном взгляде')}<p class="section-intro">Восемь ключевых этапов — от личной цели к большим возможностям для людей.</p><ol class="timeline">${stages.map(([id,title,copy,art],i)=>`<li class="${i===3||i===7?'gold-stage':''}"><a class="scene-card stage" data-step href="#${id}"><span class="step-number">${i+1}</span>${pic(art)}<div class="card-copy"><h3>${title}</h3><p>${copy}</p><span class="text-link">Подробнее ${arrow}</span></div></a></li>`).join('')}</ol></div></section>`;
const origin=`<section class="section chapters"><div class="wrap"><article class="origin" id="dream" data-chapter><div class="origin-story">${pic('dream','Человек с рюкзаком у горного озера','origin-art')}<div class="origin-copy"><h2>С чего всё началось</h2><p class="eyebrow">ГЛАВА 1</p><p>${stages[0][5]}</p>${btn('#first-step','Читать полную историю')}</div></div><blockquote><span class="quote-mark">“</span><p>Мы верим, что мечты<br>не должны оставаться мечтами.<br>Они должны работать<br>на лучший мир.</p><cite>Station for Humanity</cite>${pic('earth','','quote-art')}</blockquote></article><div class="chapter-grid">${[['factory','Первые реальные проекты','ГЛАВЫ 2–4','От идеи к прототипам. От прототипов — к работающим решениям.','first-step','Узнать больше'],['people','Другие люди и мечты','ГЛАВЫ 5–6','Знания, навыки и полезная работа объединяют людей вокруг настоящих задач.','people','Присоединиться к сообществу'],['earth','Куда мы идём дальше','ГЛАВЫ 7–8','Global Dream Factory и Dream Station — следующий горизонт. Одна планета. Тысячи мечт.','global','Исследовать будущее']].map(([art,title,chapter,copy,id,label])=>`<a class="scene-card chapter-card" href="#${id}"><div class="chapter-title"><h3>${title}</h3><span class="eyebrow">${chapter}</span></div>${pic(art)}<div class="card-copy"><p>${copy}</p><span class="text-link">${label} ${arrow}</span></div></a>`).join('')}</div><div class="chapter-details">${stages.slice(1).map(([id,title,copy,art,heading,text],i)=>`<details id="${id}" data-chapter><summary><span class="detail-number">${String(i+2).padStart(2,'0')}</span><span>${heading}<small>${title}</small></span><span class="expand" aria-hidden="true">+</span></summary><div class="detail-content">${pic(art)}<div><p>${text}</p>${id==='digital-factory'?btn(factory,'Перейти в Digital Factory',true):id==='dream-fund'?btn(LIVE+'/#social','Прочитать правила'):id==='first-result'?btn(LIVE+'/#dream001','Открыть публичный кейс'):id==='people'?btn(join,'Получить Founding Ticket',true):''}</div></div></details>`).join('')}</div></div></section>`;
const mission=`<section class="mission">${pic('earth','','mission-art')}<div class="wrap mission-inner"><div><p class="eyebrow">ВМЕСТЕ МЫ СОЗДАЁМ ЛУЧШЕЕ ЗАВТРА</p><h2>Присоединяйтесь к миссии</h2><p>Станьте частью сообщества, которое превращает<br class="desktop-break"> мечты в реальные дела. Люди. Технологии. Возможности.</p></div><div>${btn(join,'Стать частью мечты',true)}<p class="handwritten">Одна планета.<br>Тысячи мечт. ♡</p></div></div></section>`;
const story=head('История большой мечты')+header(true)+`<main id="main">${storyHero}${timeline}${origin}${mission}</main>`+footer(true)+'</body></html>';
await writeFile(new URL('index.html',import.meta.url),home);
await writeFile(new URL('story.html',import.meta.url),story);
console.log('Built two static pages: index.html, story.html');
