import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;const SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;const service=createClient(SUPABASE_URL,SERVICE_ROLE_KEY,{auth:{persistSession:false}});
const ORIGINS=new Set(["https://stationforhumanity.com","https://www.stationforhumanity.com"]);const READ_ROLES=new Set(['operator','finance','risk','admin']);
function cors(o:string|null){const x=o&&ORIGINS.has(o)?o:'https://stationforhumanity.com';return{'Access-Control-Allow-Origin':x,'Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Vary':'Origin'}}
function json(s:number,b:any,o:string|null){return new Response(JSON.stringify(b),{status:s,headers:{...cors(o),'Content-Type':'application/json; charset=utf-8'}})}
function safe(v:any,n=500){return String(v??'').trim().slice(0,n)}
async function tg(token:string,method:string,body:any={}){const r=await fetch(`https://api.telegram.org/bot${token}/${method}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(!r.ok||j?.ok===false)throw new Error(j?.description||`telegram_${r.status}`);return j.result}
async function instance(body:any){if(body.instance_id){const {data}=await service.from('leadbot_instances').select('*').eq('id',body.instance_id).maybeSingle();return data}if(body.order_no){const {data:o}=await service.from('orders').select('id').eq('order_no',Number(body.order_no)).maybeSingle();if(!o)return null;const {data}=await service.from('leadbot_instances').select('*').eq('order_id',o.id).maybeSingle();return data}const {data}=await service.from('leadbot_instances').select('*').order('created_at',{ascending:false}).limit(1).maybeSingle();return data}
async function snapshot(i:any){const {data:r}=await service.rpc('leadbot_refresh_readiness',{p_instance_id:i.id});const {data:row}=await service.from('leadbot_instances').select('id,instance_no,order_id,factory_request_id,product_code,public_slug,status,business_name,business_type,config,features,readiness,created_at,updated_at,activated_at,delivered_at').eq('id',i.id).single();const {data:o}=await service.from('orders').select('order_no,status,quoted_amount,currency,test_mode').eq('id',i.order_id).single();const {data:f}=await service.from('factory_requests').select('request_no,status,amount,currency').eq('id',i.factory_request_id).maybeSingle();const {data:leads}=await service.from('leadbot_leads').select('id,lead_no,flow_code,contact,answers,estimate,status,sync_state,created_at').eq('instance_id',i.id).order('created_at',{ascending:false}).limit(20);const {data:outbox}=await service.from('leadbot_outbox').select('id,lead_id,sink,status,attempts,last_error,created_at,updated_at').eq('instance_id',i.id).order('created_at',{ascending:false}).limit(50);return{instance:{...row,readiness:r||row.readiness},order:o,factory:f,leads:leads||[],outbox:outbox||[]}}
function secureUrl(kind:string,value:string){if(!['google_sheets_url','crm_url','webhook_url','ai_base_url'].includes(kind))return true;try{const u=new URL(value);return u.protocol==='https:'}catch{return false}}
function claimCode(){const a=new Uint32Array(1);crypto.getRandomValues(a);return String(100000+(a[0]%900000))}
Deno.serve(async req=>{const origin=req.headers.get('origin');if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(origin)});if(req.method!=='POST')return json(405,{ok:false,error:'method_not_allowed'},origin);if(origin&&!ORIGINS.has(origin))return json(403,{ok:false,error:'origin_not_allowed'},origin);const token=(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,'');const {data:u,error:ue}=await service.auth.getUser(token);if(ue||!u?.user)return json(401,{ok:false,error:'invalid_session'},origin);const {data:p}=await service.from('profiles').select('role,status').eq('id',u.user.id).maybeSingle();if(!p||p.status!=='active'||!READ_ROLES.has(p.role))return json(403,{ok:false,error:'operator_access_required'},origin);let body:any={};try{body=await req.json()}catch{return json(400,{ok:false,error:'invalid_json'},origin)}const action=safe(body.action,50);const i=await instance(body);if(!i)return json(404,{ok:false,error:'leadbot_instance_not_found'},origin);
if(action==='snapshot')return json(200,{ok:true,...await snapshot(i),role:p.role},origin);if(p.role!=='admin')return json(403,{ok:false,error:'admin_required'},origin);
if(action==='set_secret'){const kind=safe(body.kind,50),value=safe(body.value,10000);const allowed=new Set(['bot_token','google_sheets_url','crm_url','crm_token','webhook_url','webhook_token','ai_api_key','ai_base_url','ai_model']);if(!allowed.has(kind)||!value)return json(400,{ok:false,error:'invalid_secret'},origin);if(!secureUrl(kind,value))return json(400,{ok:false,error:'https_url_required'},origin);let telegram:any=null;if(kind==='bot_token'){try{telegram=await tg(value,'getMe')}catch(e){return json(400,{ok:false,error:'telegram_token_invalid',detail:safe((e as any)?.message||e)},origin)}}const {error}=await service.rpc('leadbot_store_secret',{p_instance_id:i.id,p_kind:kind,p_value:value});if(error)return json(500,{ok:false,error:'secret_store_failed',detail:error.message},origin);const {data:r}=await service.rpc('leadbot_refresh_readiness',{p_instance_id:i.id});await service.from('audit_log').insert({actor_user_id:u.user.id,action:'leadbot.secret_configured',entity_type:'leadbot_instance',entity_id:i.id,reason:`Configured ${kind}`,metadata:{kind,order_id:i.order_id}});return json(200,{ok:true,kind,telegram,readiness:r},origin)}
if(action==='generate_claim'){const code=claimCode();await service.rpc('leadbot_store_secret',{p_instance_id:i.id,p_kind:'manager_claim_code',p_value:code});const expires=new Date(Date.now()+30*60_000).toISOString();await service.from('leadbot_instances').update({readiness:{...(i.readiness||{}),claim_expires_at:expires}}).eq('id',i.id);return json(200,{ok:true,claim_code:code,expires_at:expires,command:`/claim ${code}`},origin)}
if(action==='activate'){const {data:s}=await service.rpc('leadbot_get_secrets',{p_instance_id:i.id});if(!s?.bot_token||!s?.webhook_secret)return json(409,{ok:false,error:'core_credentials_missing'},origin);let me:any;try{me=await tg(s.bot_token,'getMe')}catch(e){return json(400,{ok:false,error:'telegram_token_invalid',detail:safe((e as any)?.message||e)},origin)}const webhook=`${SUPABASE_URL}/functions/v1/leadbot-telegram?i=${encodeURIComponent(i.public_slug)}`;try{await tg(s.bot_token,'setWebhook',{url:webhook,secret_token:s.webhook_secret,allowed_updates:['message','callback_query'],drop_pending_updates:true})}catch(e){return json(502,{ok:false,error:'telegram_set_webhook_failed',detail:safe((e as any)?.message||e)},origin)}await service.from('leadbot_instances').update({status:'active',activated_at:new Date().toISOString()}).eq('id',i.id);const {data:r}=await service.rpc('leadbot_refresh_readiness',{p_instance_id:i.id});await service.from('audit_log').insert({actor_user_id:u.user.id,action:'leadbot.activated',entity_type:'leadbot_instance',entity_id:i.id,reason:'Telegram webhook activated',metadata:{order_id:i.order_id,bot_username:me?.username||null,webhook}});return json(200,{ok:true,bot:{id:me?.id,username:me?.username,first_name:me?.first_name},webhook_active:true,readiness:r},origin)}
if(action==='deactivate'){const {data:s}=await service.rpc('leadbot_get_secrets',{p_instance_id:i.id});if(s?.bot_token)try{await tg(s.bot_token,'deleteWebhook',{drop_pending_updates:false})}catch{}await service.from('leadbot_instances').update({status:'paused'}).eq('id',i.id);return json(200,{ok:true,status:'paused'},origin)}
if(action==='configure_calculator'){const base=Number(body.base||0),perPoint=Number(body.per_point||0),perM2=Number(body.per_m2||0);if([base,perPoint,perM2].some(x=>!Number.isFinite(x)||x<0||x>10000000)||base+perPoint+perM2<=0)return json(400,{ok:false,error:'invalid_rates'},origin);const multipliers=(body.object_multipliers&&typeof body.object_multipliers==='object')?body.object_multipliers:{};const cfg={...(i.config||{}),calculator:{...(i.config?.calculator||{}),enabled:true,configured:true,currency:'RUB',rates:{base,per_point:perPoint,per_m2:perM2,object_multipliers:multipliers},configured_at:new Date().toISOString()}};await service.from('leadbot_instances').update({config:cfg}).eq('id',i.id);const {data:r}=await service.rpc('leadbot_refresh_readiness',{p_instance_id:i.id});await service.from('audit_log').insert({actor_user_id:u.user.id,action:'leadbot.calculator_configured',entity_type:'leadbot_instance',entity_id:i.id,reason:'Calculator rates configured',metadata:{base,per_point:perPoint,per_m2:perM2}});return json(200,{ok:true,readiness:r},origin)}
if(action==='test_notification'){const {data:s}=await service.rpc('leadbot_get_secrets',{p_instance_id:i.id});if(!s?.bot_token||!s?.manager_chat_id)return json(409,{ok:false,error:'manager_or_bot_missing'},origin);await tg(s.bot_token,'sendMessage',{chat_id:s.manager_chat_id,text:`✅ Station LeadBot ${i.public_slug}: тестовое уведомление. Канал менеджера подключён.`});return json(200,{ok:true},origin)}return json(400,{ok:false,error:'unknown_action'},origin)});