import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const S=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,db=createClient(S,K,{auth:{persistSession:false}});
const ORIGINS=new Set(["https://stationforhumanity.com","https://www.stationforhumanity.com","http://localhost:3000","http://127.0.0.1:3000"]),PLATFORM=new Set(["admin","operator"]),ROLES=new Set(["owner","manager"]);const safe=(v:any,n=500)=>String(v??"").trim().slice(0,n);
function cors(o:string|null){const x=o&&ORIGINS.has(o)?o:"https://stationforhumanity.com";return{"Access-Control-Allow-Origin":x,"Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Vary":"Origin"}}function out(s:number,b:any,o:string|null){return new Response(JSON.stringify(b),{status:s,headers:{...cors(o),"content-type":"application/json; charset=utf-8","cache-control":"no-store"}})}
async function ctx(uid:string,slug:string){const {data:p}=await db.from("profiles").select("role,status").eq("id",uid).maybeSingle(),platform=!!p&&p.status==="active"&&PLATFORM.has(p.role);const {data:w}=await db.from("rpk_workspaces").select("id,slug,name").eq("slug",slug).maybeSingle();if(!w)return null;if(platform)return{w,role:"platform_admin",platform:true};const {data:m}=await db.from("rpk_members").select("role,status").eq("workspace_id",w.id).eq("user_id",uid).maybeSingle();return m?.status==="active"?{w,role:m.role,platform:false}:null}
async function userLabel(id:string|null){if(!id)return{email:"system",name:"System"};try{const {data}=await db.auth.admin.getUserById(id),u=data.user;return{email:u?.email||"unknown",name:u?.user_metadata?.full_name||u?.user_metadata?.name||u?.email||"Пользователь"}}catch{return{email:"unknown",name:"Пользователь"}}}
async function findEmail(email:string){for(let page=1;page<=20;page++){const {data,error}=await db.auth.admin.listUsers({page,perPage:100});if(error)throw error;const x=data.users.find((u:any)=>(u.email||"").toLowerCase()===email);if(x)return x;if(data.users.length<100)break}return null}
async function registry(wid:string){const {data}=await db.from("business_workspace_registry").select("id").eq("source_kind","rpk").eq("source_workspace_id",wid).maybeSingle();return data}
async function audit(uid:string,action:string,wid:string,meta:any={}){await db.from("audit_log").insert({actor_user_id:uid,action,entity_type:"rpk_workspace",entity_id:wid,reason:"RPK team action",metadata:{workspace_id:wid,...meta}})}
Deno.serve(async req=>{const o=req.headers.get("origin");if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(o)});if(req.method!=="POST")return out(405,{ok:false,error:"method_not_allowed"},o);if(o&&!ORIGINS.has(o))return out(403,{ok:false,error:"origin_not_allowed"},o);const jwt=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,""),{data:u,error}=await db.auth.getUser(jwt);if(error||!u.user)return out(401,{ok:false,error:"invalid_session"},o);let b:any={};try{b=await req.json()}catch{return out(400,{ok:false,error:"invalid_json"},o)}const c=await ctx(u.user.id,safe(b.workspace_slug||"focus-biysk",100));if(!c)return out(403,{ok:false,error:"workspace_access_denied"},o);const {w,role}=c,action=safe(b.action,60),owner=["owner","platform_admin"].includes(role);
if(action==="snapshot"){const {data:members}=await db.from("rpk_members").select("workspace_id,user_id,role,status,created_at,updated_at").eq("workspace_id",w.id).order("created_at"),rich=[] as any[];for(const m of members||[]){const a=await userLabel(m.user_id);rich.push({...m,...a})}if(c.platform&&!rich.some(x=>x.user_id===u.user.id)){const a=await userLabel(u.user.id);rich.unshift({user_id:u.user.id,role:"platform_admin",status:"active",...a})}const r=await registry(w.id);let settings:any=null;if(r){const {data}=await db.from("business_workspace_settings").select("declared_team_size,community_enabled").eq("workspace_id",r.id).maybeSingle();settings=data}const {data:logs}=await db.from("audit_log").select("actor_user_id,action,entity_type,entity_id,before_state,after_state,metadata,created_at").contains("metadata",{workspace_id:w.id}).order("created_at",{ascending:false}).limit(Math.min(200,Math.max(10,Number(b.limit||100))));const activity=[] as any[];for(const x of logs||[]){activity.push({...x,actor:await userLabel(x.actor_user_id)})}return out(200,{ok:true,workspace:w,access_role:role,allowed_roles:[...ROLES],members:rich,team:{declared_size:settings?.declared_team_size??null,active_crm_users:(members||[]).filter((x:any)=>x.status==='active').length,community_enabled:settings?.community_enabled!==false},activity},o)}
if(action==="set_team_size"){if(!owner)return out(403,{ok:false,error:"owner_role_required"},o);const n=Number(b.declared_team_size);if(!Number.isInteger(n)||n<1||n>5000)return out(400,{ok:false,error:"team_size_must_be_1_to_5000"},o);const r=await registry(w.id);if(!r)return out(404,{ok:false,error:"business_registry_missing"},o);const {error}=await db.from("business_workspace_settings").upsert({workspace_id:r.id,declared_team_size:n,updated_by:u.user.id,updated_at:new Date().toISOString()},{onConflict:"workspace_id"});if(error)return out(500,{ok:false,error:"team_size_update_failed"},o);await audit(u.user.id,"rpk.team_size_updated",w.id,{declared_team_size:n});return out(200,{ok:true},o)}
if(action==="add_member"){if(!owner)return out(403,{ok:false,error:"owner_role_required"},o);const email=safe(b.email,240).toLowerCase(),newRole=safe(b.role,30);if(!email.includes("@"))return out(400,{ok:false,error:"valid_email_required"},o);if(!ROLES.has(newRole))return out(400,{ok:false,error:"invalid_member_role",allowed:[...ROLES]},o);let target=await findEmail(email),invited=false;if(!target){const next=encodeURIComponent(`/factory/rpk/?w=${w.slug}`),{data,error}=await db.auth.admin.inviteUserByEmail(email,{redirectTo:`https://stationforhumanity.com/business/welcome/?next=${next}`});if(error)return out(500,{ok:false,error:"invite_failed",detail:error.message},o);target=data.user;invited=true}const {data,error:e}=await db.from("rpk_members").upsert({workspace_id:w.id,user_id:target.id,role:newRole,status:"active",updated_at:new Date().toISOString()},{onConflict:"workspace_id,user_id"}).select("workspace_id,user_id,role,status").single();if(e)return out(500,{ok:false,error:"member_upsert_failed",detail:e.message},o);await audit(u.user.id,"rpk.member_added",w.id,{target_user_id:target.id,target_email:email,role:newRole,invited});return out(200,{ok:true,member:{...data,email},invited},o)}
if(action==="set_member_role"){if(!owner)return out(403,{ok:false,error:"owner_role_required"},o);const id=safe(b.user_id,80),newRole=safe(b.role,30);if(!ROLES.has(newRole))return out(400,{ok:false,error:"invalid_member_role"},o);if(id===u.user.id&&newRole!=="owner")return out(409,{ok:false,error:"cannot_downgrade_yourself"},o);const {data,error}=await db.from("rpk_members").update({role:newRole,updated_at:new Date().toISOString()}).eq("workspace_id",w.id).eq("user_id",id).select("user_id,role,status").maybeSingle();if(error||!data)return out(404,{ok:false,error:"member_not_found"},o);await audit(u.user.id,"rpk.member_role_changed",w.id,{target_user_id:id,role:newRole});return out(200,{ok:true,member:data},o)}
if(action==="disable_member"){if(!owner)return out(403,{ok:false,error:"owner_role_required"},o);const id=safe(b.user_id,80);if(id===u.user.id)return out(409,{ok:false,error:"cannot_disable_yourself"},o);const {data,error}=await db.from("rpk_members").update({status:"disabled",updated_at:new Date().toISOString()}).eq("workspace_id",w.id).eq("user_id",id).select("user_id,role,status").maybeSingle();if(error||!data)return out(404,{ok:false,error:"member_not_found"},o);await audit(u.user.id,"rpk.member_disabled",w.id,{target_user_id:id});return out(200,{ok:true,member:data},o)}return out(400,{ok:false,error:"unknown_action"},o)});