import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {createClient} from "npm:@supabase/supabase-js@2";
const S=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,A="https://platform-api2.max.ru";
const db=createClient(S,K,{auth:{persistSession:false}}),ORIGINS=new Set(["https://stationforhumanity.com","https://www.stationforhumanity.com"]);
const safe=(v:any,n=500)=>String(v??"").trim().slice(0,n);
function cors(o:string|null){const x=o&&ORIGINS.has(o)?o:"https://stationforhumanity.com";return{"Access-Control-Allow-Origin":x,"Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Vary":"Origin"}}
function out(s:number,b:any,o:string|null){return new Response(JSON.stringify(b),{status:s,headers:{...cors(o),"content-type":"application/json; charset=utf-8"}})}
async function max(t:string,p:string,m="GET",b?:any){const r=await fetch(A+p,{method:m,headers:{Authorization:t,...(b?{"content-type":"application/json"}:{})},...(b?{body:JSON.stringify(b)}:{})});const j=await r.json().catch(()=>({}));if(!r.ok||j?.success===false)throw Error(j?.message||`max_${m}_${r.status}`);return j}
async function inst(b:any){if(b.instance_id){const {data}=await db.from("leadbot_instances").select("*").eq("id",b.instance_id).maybeSingle();return data}if(b.order_no){const {data:o}=await db.from("orders").select("id").eq("order_no",Number(b.order_no)).maybeSingle();if(!o)return null;const {data}=await db.from("leadbot_instances").select("*").eq("order_id",o.id).maybeSingle();return data}const {data}=await db.from("leadbot_instances").select("*").order("created_at",{ascending:false}).limit(1).maybeSingle();return data}
function secret(){return (crypto.randomUUID()+crypto.randomUUID()).replaceAll("-","")}
Deno.serve(async req=>{const origin=req.headers.get("origin");if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(origin)});if(req.method!=="POST")return out(405,{ok:false,error:"method_not_allowed"},origin);if(origin&&!ORIGINS.has(origin))return out(403,{ok:false,error:"origin_not_allowed"},origin);const jwt=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");const {data:u,error:ue}=await db.auth.getUser(jwt);if(ue||!u?.user)return out(401,{ok:false,error:"invalid_session"},origin);const {data:p}=await db.from("profiles").select("role,status").eq("id",u.user.id).maybeSingle();if(!p||p.status!=="active"||p.role!=="admin")return out(403,{ok:false,error:"admin_required"},origin);let b:any;try{b=await req.json()}catch{return out(400,{ok:false,error:"invalid_json"},origin)}const i=await inst(b);if(!i)return out(404,{ok:false,error:"leadbot_instance_not_found"},origin);const action=safe(b.action,50);
if(action==="snapshot"){const {data:r}=await db.rpc("leadbot_refresh_readiness",{p_instance_id:i.id});const {data:s}=await db.rpc("leadbot_get_secrets",{p_instance_id:i.id});let bot=null,subscriptions=[];if(s?.max_bot_token){try{bot=await max(s.max_bot_token,"/me");const q=await max(s.max_bot_token,"/subscriptions");subscriptions=q?.subscriptions||[]}catch{}}return out(200,{ok:true,instance_id:i.id,order_id:i.order_id,public_slug:i.public_slug,status:i.status,business_name:i.business_name,readiness:r||i.readiness,bot:bot?{user_id:bot.user_id,username:bot.username,first_name:bot.first_name}:null,subscriptions},origin)}
if(action==="set_token"){const value=safe(b.value,10000);if(value.length<20)return out(400,{ok:false,error:"invalid_token"},origin);let me;try{me=await max(value,"/me")}catch(e){return out(400,{ok:false,error:"max_token_invalid",detail:safe((e as any)?.message||e)},origin)}const {error:e}=await db.rpc("leadbot_store_secret",{p_instance_id:i.id,p_kind:"max_bot_token",p_value:value});if(e)return out(500,{ok:false,error:"secret_store_failed",detail:e.message},origin);const {data:r}=await db.rpc("leadbot_refresh_readiness",{p_instance_id:i.id});await db.from("audit_log").insert({actor_user_id:u.user.id,action:"leadbot.max_token_configured",entity_type:"leadbot_instance",entity_id:i.id,reason:"MAX token validated through GET /me and stored in Vault",metadata:{order_id:i.order_id,bot_user_id:me?.user_id||null,bot_username:me?.username||null}});return out(200,{ok:true,bot:{user_id:me?.user_id,username:me?.username,first_name:me?.first_name},readiness:r},origin)}
if(action==="set_manager"){const id=safe(b.user_id,100);if(!/^-?\d+$/.test(id))return out(400,{ok:false,error:"invalid_manager_user_id"},origin);const {error:e}=await db.rpc("leadbot_store_secret",{p_instance_id:i.id,p_kind:"max_manager_user_id",p_value:id});if(e)return out(500,{ok:false,error:"secret_store_failed",detail:e.message},origin);const {data:r}=await db.rpc("leadbot_refresh_readiness",{p_instance_id:i.id});return out(200,{ok:true,readiness:r},origin)}
if(action==="activate"){let {data:s}=await db.rpc("leadbot_get_secrets",{p_instance_id:i.id});if(!s?.max_bot_token)return out(409,{ok:false,error:"max_token_missing"},origin);let me;try{me=await max(s.max_bot_token,"/me")}catch(e){return out(400,{ok:false,error:"max_token_invalid",detail:safe((e as any)?.message||e)},origin)}let wh=s.max_webhook_secret;if(!wh){wh=secret();const {error:e}=await db.rpc("leadbot_store_secret",{p_instance_id:i.id,p_kind:"max_webhook_secret",p_value:wh});if(e)return out(500,{ok:false,error:"webhook_secret_store_failed",detail:e.message},origin);s={...s,max_webhook_secret:wh}}const url=`${S}/functions/v1/leadbot-max?i=${encodeURIComponent(i.public_slug)}`;try{await max(s.max_bot_token,"/subscriptions","POST",{url,update_types:["message_created","bot_started"],secret:wh})}catch(e){return out(502,{ok:false,error:"max_subscription_failed",detail:safe((e as any)?.message||e)},origin)}await db.from("leadbot_instances").update({status:"active",activated_at:i.activated_at||new Date().toISOString()}).eq("id",i.id);const {data:r}=await db.rpc("leadbot_refresh_readiness",{p_instance_id:i.id});await db.from("audit_log").insert({actor_user_id:u.user.id,action:"leadbot.max_activated",entity_type:"leadbot_instance",entity_id:i.id,reason:"MAX production webhook subscribed",metadata:{order_id:i.order_id,bot_user_id:me?.user_id||null,bot_username:me?.username||null,webhook:url,update_types:["message_created","bot_started"]}});return out(200,{ok:true,bot:{user_id:me?.user_id,username:me?.username,first_name:me?.first_name},webhook:url,readiness:r},origin)}
if(action==="test_manager"){const {data:s}=await db.rpc("leadbot_get_secrets",{p_instance_id:i.id});if(!s?.max_bot_token||!s?.max_manager_user_id)return out(409,{ok:false,error:"max_manager_or_token_missing"},origin);await max(s.max_bot_token,`/messages?user_id=${encodeURIComponent(String(s.max_manager_user_id))}`,"POST",{text:`✅ Station LeadBot ${i.public_slug}: MAX-канал менеджера подключён.`});return out(200,{ok:true},origin)}
return out(400,{ok:false,error:"unknown_action"},origin)});