-- Station for Humanity — shadow-governance registry.
-- Non-binding founding-stage infrastructure: proposals are public-read only;
-- appeals/conflicts are private by default; binding voting and ratification remain OFF.

create table if not exists public.governance_settings (
  id smallint primary key default 1 check (id = 1),
  shadow_mode boolean not null default true,
  binding_votes_enabled boolean not null default false,
  constitution_ratified boolean not null default false,
  ratified_version text,
  notes text not null default 'Founding-stage shadow governance. No binding constitutional voting is active.',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
insert into public.governance_settings(id) values (1) on conflict (id) do nothing;

create table if not exists public.governance_proposals (
  id uuid primary key default gen_random_uuid(),
  proposal_no bigint generated by default as identity unique not null,
  title text not null check (length(title) between 3 and 240),
  summary text not null check (length(summary) between 3 and 4000),
  body_markdown text not null default '',
  decision_class text not null check (decision_class in ('O','E','R','C','X')),
  protection_level text not null default 'unclassified' check (protection_level in ('L0','L1A','L1B','L2A','L2B','unclassified')),
  status text not null default 'draft' check (status in ('draft','public_review','accepted_as_draft','rejected','withdrawn','ratified')),
  is_public boolean not null default false,
  proposer_user_id uuid,
  source_path text,
  source_commit_sha text,
  review_opens_at timestamptz,
  review_closes_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (review_closes_at is null or review_opens_at is null or review_closes_at > review_opens_at)
);

create table if not exists public.governance_proposal_versions (
  id uuid primary key default gen_random_uuid(),
  proposal_id uuid not null references public.governance_proposals(id) on delete cascade,
  version_no integer not null check (version_no > 0),
  title text not null,
  summary text not null,
  body_markdown text not null default '',
  change_summary text not null default '',
  source_path text,
  source_commit_sha text,
  created_by uuid,
  created_at timestamptz not null default now(),
  unique(proposal_id, version_no)
);

create table if not exists public.governance_reviews (
  id uuid primary key default gen_random_uuid(),
  proposal_id uuid not null references public.governance_proposals(id) on delete cascade,
  reviewer_user_id uuid,
  reviewer_role text not null default 'participant' check (reviewer_role in ('participant','builder','partner','auditor','rights_review','founder','operator','ai_advisory')),
  stance text not null check (stance in ('support','concern','oppose','neutral','needs_revision')),
  rationale text not null check (length(rationale) between 1 and 10000),
  is_public boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.governance_conflict_disclosures (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  proposal_id uuid references public.governance_proposals(id) on delete set null,
  status text not null default 'active' check (status in ('active','resolved','withdrawn')),
  public_summary text not null check (length(public_summary) between 1 and 4000),
  private_details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.appeal_cases (
  id uuid primary key default gen_random_uuid(),
  case_no bigint generated by default as identity unique not null,
  subject_user_id uuid,
  opened_by_user_id uuid,
  source_type text not null check (source_type in ('automated_decision','operator_decision','account_action','economic_decision','reputation','eligibility','other')),
  source_id text,
  reason_code text not null,
  description text not null check (length(description) between 1 and 20000),
  status text not null default 'submitted' check (status in ('submitted','triage','under_review','awaiting_information','resolved','rejected','withdrawn')),
  assigned_reviewer_user_id uuid,
  outcome text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table if not exists public.appeal_events (
  id uuid primary key default gen_random_uuid(),
  appeal_id uuid not null references public.appeal_cases(id) on delete cascade,
  event_type text not null,
  actor_user_id uuid,
  note text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_governance_proposals_public on public.governance_proposals(is_public,status,proposal_no desc);
create index if not exists idx_governance_versions_proposal on public.governance_proposal_versions(proposal_id,version_no desc);
create index if not exists idx_governance_reviews_proposal on public.governance_reviews(proposal_id,created_at desc);
create index if not exists idx_appeal_cases_subject on public.appeal_cases(subject_user_id,created_at desc);
create index if not exists idx_appeal_cases_status on public.appeal_cases(status,created_at);
create index if not exists idx_appeal_events_case on public.appeal_events(appeal_id,created_at);

alter table public.governance_settings enable row level security;
alter table public.governance_proposals enable row level security;
alter table public.governance_proposal_versions enable row level security;
alter table public.governance_reviews enable row level security;
alter table public.governance_conflict_disclosures enable row level security;
alter table public.appeal_cases enable row level security;
alter table public.appeal_events enable row level security;

revoke all on public.governance_settings from anon, authenticated;
revoke all on public.governance_proposals from anon, authenticated;
revoke all on public.governance_proposal_versions from anon, authenticated;
revoke all on public.governance_reviews from anon, authenticated;
revoke all on public.governance_conflict_disclosures from anon, authenticated;
revoke all on public.appeal_cases from anon, authenticated;
revoke all on public.appeal_events from anon, authenticated;

grant select on public.governance_settings to anon, authenticated;
grant select on public.governance_proposals to anon, authenticated;
grant select on public.governance_proposal_versions to anon, authenticated;
grant select on public.governance_reviews to anon, authenticated;

grant select,insert,update,delete on public.governance_settings to service_role;
grant select,insert,update,delete on public.governance_proposals to service_role;
grant select,insert,update,delete on public.governance_proposal_versions to service_role;
grant select,insert,update,delete on public.governance_reviews to service_role;
grant select,insert,update,delete on public.governance_conflict_disclosures to service_role;
grant select,insert,update,delete on public.appeal_cases to service_role;
grant select,insert,update,delete on public.appeal_events to service_role;
grant usage,select,update on sequence public.governance_proposals_proposal_no_seq to service_role;
grant usage,select,update on sequence public.appeal_cases_case_no_seq to service_role;

create policy governance_settings_public_read on public.governance_settings for select to anon, authenticated using (true);
create policy governance_proposals_public_read on public.governance_proposals for select to anon, authenticated using (is_public=true and status in ('public_review','accepted_as_draft','ratified'));
create policy governance_versions_public_read on public.governance_proposal_versions for select to anon, authenticated using (exists(select 1 from public.governance_proposals gp where gp.id=proposal_id and gp.is_public=true and gp.status in ('public_review','accepted_as_draft','ratified')));
create policy governance_reviews_public_read on public.governance_reviews for select to anon, authenticated using (is_public=true and exists(select 1 from public.governance_proposals gp where gp.id=proposal_id and gp.is_public=true and gp.status in ('public_review','accepted_as_draft','ratified')));

create trigger trg_governance_settings_updated_at before update on public.governance_settings for each row execute function public.set_updated_at();
create trigger trg_governance_proposals_updated_at before update on public.governance_proposals for each row execute function public.set_updated_at();
create trigger trg_governance_conflicts_updated_at before update on public.governance_conflict_disclosures for each row execute function public.set_updated_at();
create trigger trg_appeal_cases_updated_at before update on public.appeal_cases for each row execute function public.set_updated_at();

insert into public.governance_proposals(title,summary,decision_class,protection_level,status,is_public,source_path,source_commit_sha,review_opens_at)
select 'Constitution Draft 0.3','Public working review of the expanded Station for Humanity Constitution. Only Article 0 is immutable today. This proposal is not ratification and creates no binding voting authority.','C','unclassified','public_review',true,'CONSTITUTION.md','b736d8fd3da2079079655aeac1d3cc8affd171bf',now()
where not exists(select 1 from public.governance_proposals where source_path='CONSTITUTION.md' and status='public_review');

insert into public.governance_proposals(title,summary,decision_class,protection_level,status,is_public,source_path,source_commit_sha,review_opens_at)
select 'Governance Working Draft 0.4','Shadow-governance design for decision classes, representative bodies, founding transition, anti-capture rules, appeal and audit. It is deliberately non-binding while the real participant base is still small.','C','L2B','public_review',true,'GOVERNANCE.md','3eb53b86a79d67d07b58d366df33f25b04102963',now()
where not exists(select 1 from public.governance_proposals where source_path='GOVERNANCE.md' and status='public_review');

insert into public.governance_proposal_versions(proposal_id,version_no,title,summary,source_path,source_commit_sha,change_summary)
select id,1,title,summary,source_path,source_commit_sha,'Initial public shadow-governance registry version.' from public.governance_proposals gp
where gp.source_path in ('CONSTITUTION.md','GOVERNANCE.md')
and not exists(select 1 from public.governance_proposal_versions v where v.proposal_id=gp.id and v.version_no=1);

-- Close accidental public RPC exposure if the legacy LeadBot normalization trigger function exists.
do $$
begin
  if to_regprocedure('public.leadbot_outbox_pull_feed_normalize()') is not null then
    execute 'revoke all on function public.leadbot_outbox_pull_feed_normalize() from public';
    execute 'revoke all on function public.leadbot_outbox_pull_feed_normalize() from anon';
    execute 'revoke all on function public.leadbot_outbox_pull_feed_normalize() from authenticated';
    execute 'grant execute on function public.leadbot_outbox_pull_feed_normalize() to service_role';
  end if;
end $$;
