import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const service=createClient(SUPABASE_URL,SERVICE_ROLE_KEY,{auth:{persistSession:false}});
function json(status:number,body:any){return new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json; charset=utf-8"}})}
function safe(v:any,n=1000){return String(v??'').slice(0,n)}
async function sinkConfig(instanceId:string,sink:string){const {data:s,error}=await service.rpc('leadbot_get_secrets',{p_instance_id:instanceId});if(error)throw new Error(`secret_read:${error.message}`);if(sink==='google_sheets')return{url:s?.google_sheets_url||'',token:''};if(sink==='crm')return{url:s?.crm_url||'',token:s?.crm_token||''};if(sink==='webhook')return{url:s?.webhook_url||'',token:s?.webhook_token||''};throw new Error('unsupported_sink')}
async function deliver(row:any){const cfg=await sinkConfig(row.instance_id,row.sink);if(!cfg.url){await service.from('leadbot_outbox').update({status:'failed',last_error:'credentials_missing',next_attempt_at:new Date(Date.now()+15*60_000).toISOString()}).eq('id',row.id);return{state:'waiting_credentials'}}const headers:any={'Content-Type':'application/json','Idempotency-Key':`${row.lead_id}:${row.sink}`};if(cfg.token)headers.Authorization=`Bearer ${cfg.token}`;const r=await fetch(cfg.url,{method:'POST',headers,body:JSON.stringify(row.payload)});const text=await r.text();if(!r.ok){const attempts=Number(row.attempts||0)+1,delay=Math.min(60,5*Math.pow(2,Math.min(attempts,4)));await service.from('leadbot_outbox').update({status:'failed',attempts,last_error:`http_${r.status}:${safe(text,500)}`,next_attempt_at:new Date(Date.now()+delay*60_000).toISOString()}).eq('id',row.id);return{state:'failed',status:r.status}}await service.from('leadbot_outbox').update({status:'succeeded',attempts:Number(row.attempts||0)+1,response:{status:r.status,body:safe(text,1000)},last_error:null,updated_at:new Date().toISOString()}).eq('id',row.id);return{state:'succeeded',status:r.status}}
Deno.serve(async req=>{if(req.method!=='POST')return json(405,{ok:false,error:'method_not_allowed'});const token=req.headers.get('x-sfh-watchdog')||'';if(!token)return json(401,{ok:false,error:'missing_scheduler_token'});const {data:ok,error:ve}=await service.rpc('verify_watchdog_token',{p_token:token});if(ve||ok!==true)return json(401,{ok:false,error:'invalid_scheduler_token'});const {data:rows,error}=await service.from('leadbot_outbox').select('id,instance_id,lead_id,sink,status,attempts,next_attempt_at,payload').in('status',['pending','failed']).lte('next_attempt_at',new Date().toISOString()).order('next_attempt_at',{ascending:true}).limit(50);if(error)return json(500,{ok:false,error:'outbox_read_failed',detail:error.message});const result:any={checked:0,succeeded:0,failed:0,waiting_credentials:0,errors:[]};for(const row of rows||[]){result.checked++;try{const r=await deliver(row);if(r.state==='succeeded')result.succeeded++;else if(r.state==='waiting_credentials')result.waiting_credentials++;else result.failed++;}catch(e){result.failed++;result.errors.push({id:row.id,error:safe((e as any)?.message||e,500)})}}return json(200,{ok:true,...result})});
